import type { SkillAdvanceLevel } from "./types.js";
import { SkillSource } from "./skillSource.js";
import type {
  CareerCharacteristicAdvanceCosts,
  CharacteristicKey,
} from "./careerAdvancesReference.js";

export interface AlternateRankSkillAdvance {
  id: string;
  kind: "skill";
  skillId: string;
  level?: Exclude<SkillAdvanceLevel, "untrained">;
  cost: number;
  prerequisites?: string;
  repeatable?: boolean;
}

export interface AlternateRankTalentAdvance {
  id: string;
  kind: "talent";
  talentId: string;
  specialisation?: string;
  cost: number;
  prerequisites?: string;
}

export interface AlternateRankEliteAdvance {
  id: string;
  kind: "elite-advance";
  eliteAdvanceId: string;
}

export type AlternateRankAdvance =
  | AlternateRankSkillAdvance
  | AlternateRankTalentAdvance
  | AlternateRankEliteAdvance;

export interface AlternateRankGearGrant {
  id: string;
  referenceId: string;
  name: string;
  description: string;
}

export interface AlternateRankMeleeWeaponChoice {
  id: string;
  label: string;
  referenceIds: readonly string[];
}

export interface AlternateRankData {
  id: string;
  name: string;
  source: SkillSource;
  quote: string;
  attribution: string;
  description?: string;
  requiredCareerIds: readonly string[];
  minimumRank: number;
  minimumXp: number;
  requiredCareerPaths?: readonly string[];
  requirements: {
    maximumCorruption?: number;
    maximumInsanity?: number;
    minimumIntelligence?: number;
    minimumFellowship?: number;
    minimumBallisticSkill?: number;
    requiredSkills?: readonly string[];
    requiresInquisitorOffer?: boolean;
    requiredOriginOrTraining?: string;
    excludedOrigins?: readonly string[];
    otherRequirements?: readonly string[];
  };
  availableAtCharacterCreation?: boolean;
  grantedTraits?: readonly string[];
  grantedGear?: readonly AlternateRankGearGrant[];
  grantedMeleeWeaponChoice?: AlternateRankMeleeWeaponChoice;
  grantedEliteAdvances?: readonly string[];
  characteristicAdvanceOverrides?: Partial<
    Record<CharacteristicKey, CareerCharacteristicAdvanceCosts>
  >;
  insanityGain?: "1d5";
  advances: readonly AlternateRankAdvance[];
}

export const ALTERNATE_RANKS: readonly AlternateRankData[] = [
  {
    id: "black-priest-of-maccabeus",
    name: "Black Priest of Maccabeus",
    source: SkillSource.IH,
    quote:
      "I walk in the footsteps of the Blessed Saint Drusus and I go about the Emperor’s work. At my word the unclean spirit baulks and the heretic withers in shame. Who, then, are you to stand against me?",
    attribution: "Prior Cornelius Agrippa, Maccabean Exorcist.",
    description:
      "In order to qualify for this path, the character must be a Cleric who either originates from Maccabeus Quintus, or with the permission (or at the behest) of their Inquisitorial masters is sent to train there during ‘downtime’ between adventures. This Career Path is particularly suited to Clerics who want a more directly combative role against the powers of the warp, or who in their character’s past have survived encounters with the Daemonic.",
    requiredCareerIds: ["cleric"],
    minimumRank: 4,
    minimumXp: 2_000,
    requirements: {
      maximumCorruption: 9,
      requiredOriginOrTraining: "Maccabeus Quintus",
      excludedOrigins: ["Mind Cleansed"],
    },
    advances: [
      { id: "command", kind: "skill", skillId: "command", cost: 100 },
      {
        id: "common-imperial-creed-20",
        kind: "skill",
        skillId: "common-imperial-creed",
        level: "+20",
        cost: 100,
        prerequisites: "Common Lore (Imperial Creed) +10",
      },
      {
        id: "deceive-10",
        kind: "skill",
        skillId: "deceive",
        level: "+10",
        cost: 100,
        prerequisites: "Deceive",
      },
      { id: "forbidden-cults", kind: "skill", skillId: "forbidden-cults", cost: 100 },
      {
        id: "forbidden-daemonology",
        kind: "skill",
        skillId: "forbidden-daemonology",
        cost: 100,
      },
      {
        id: "forbidden-daemonology-10",
        kind: "skill",
        skillId: "forbidden-daemonology",
        level: "+10",
        cost: 100,
        prerequisites: "Forbidden Lore (Daemonology)",
      },
      { id: "interrogation", kind: "skill", skillId: "interrogation", cost: 100 },
      { id: "intimidation", kind: "skill", skillId: "intimidate", cost: 100 },
      {
        id: "pilot-civilian-10",
        kind: "skill",
        skillId: "pilot-civilian",
        level: "+10",
        cost: 100,
        prerequisites: "Pilot (Civilian Craft)",
      },
      {
        id: "scholastic-legend-10",
        kind: "skill",
        skillId: "scholastic-legend",
        level: "+10",
        cost: 100,
        prerequisites: "Scholastic Lore (Legend)",
      },
      {
        id: "scholastic-occult",
        kind: "skill",
        skillId: "scholastic-occult",
        cost: 100,
      },
      {
        id: "speak-high-gothic",
        kind: "skill",
        skillId: "speak-high-gothic",
        cost: 100,
      },
      {
        id: "basic-bolt",
        kind: "talent",
        talentId: "basic-weapon-training",
        specialisation: "Bolt",
        cost: 100,
      },
      {
        id: "basic-flame",
        kind: "talent",
        talentId: "basic-weapon-training",
        specialisation: "Flame",
        cost: 100,
      },
      {
        id: "hatred-daemons",
        kind: "talent",
        talentId: "hatred",
        specialisation: "Daemons",
        cost: 100,
      },
      {
        id: "master-orator",
        kind: "talent",
        talentId: "master-orator",
        cost: 100,
        prerequisites: "Fel 30",
      },
      {
        id: "melee-chain",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Chain",
        cost: 100,
      },
      {
        id: "unshakeable-faith",
        kind: "talent",
        talentId: "unshakeable-faith",
        cost: 100,
      },
      {
        id: "sound-constitution-100",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 100,
      },
      {
        id: "command-10",
        kind: "skill",
        skillId: "command",
        level: "+10",
        cost: 200,
        prerequisites: "Command",
      },
      {
        id: "forbidden-cults-10",
        kind: "skill",
        skillId: "forbidden-cults",
        level: "+10",
        cost: 200,
        prerequisites: "Forbidden Lore (Cults)",
      },
      { id: "forbidden-warp", kind: "skill", skillId: "forbidden-warp", cost: 200 },
      {
        id: "melee-power",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Power",
        cost: 200,
      },
      {
        id: "peer-ordo-malleus",
        kind: "talent",
        talentId: "peer",
        specialisation: "Ordo Malleus",
        cost: 200,
        prerequisites: "Fel 30",
      },
      {
        id: "pistol-bolt",
        kind: "talent",
        talentId: "pistol-training",
        specialisation: "Bolt",
        cost: 200,
      },
      {
        id: "pistol-flame",
        kind: "talent",
        talentId: "pistol-training",
        specialisation: "Flame",
        cost: 200,
      },
      {
        id: "sound-constitution-200",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 200,
      },
      { id: "pure-faith", kind: "talent", talentId: "pure-faith", cost: 300 },
      {
        id: "purge-the-unclean",
        kind: "talent",
        talentId: "purge-the-unclean",
        cost: 300,
        prerequisites: "Pure Faith",
      },
      {
        id: "encarta-maleficarum",
        kind: "elite-advance",
        eliteAdvanceId: "encarta-maleficarum",
      },
    ],
  },
  {
    id: "bonded-emissary",
    name: "Bonded Emissary",
    source: SkillSource.IH,
    quote:
      "My masters regret that your harvest has failed governor and unrest stirs your little world. Perhaps you should seek assistance from the free captains as you did three years ago when you turned down our last generous offer, and with it the protection of our friendship… no? Well, unfortunately things have grown harsher in the sub-sector of late and our price now is regrettably somewhat higher…",
    attribution: "Adept-Assayer Alisha Zhou, Emissary of the Machenko Dynasty.",
    description: "",
    requiredCareerIds: ["adept", "tech-priest"],
    minimumRank: 4,
    minimumXp: 2_000,
    requirements: {
      minimumIntelligence: 30,
      minimumFellowship: 30,
    },
    advances: [
      { id: "barter", kind: "skill", skillId: "barter", cost: 100 },
      {
        id: "barter-10",
        kind: "skill",
        skillId: "barter",
        level: "+10",
        cost: 100,
        prerequisites: "Barter",
      },
      { id: "charm", kind: "skill", skillId: "charm", cost: 100 },
      {
        id: "charm-10",
        kind: "skill",
        skillId: "charm",
        level: "+10",
        cost: 100,
        prerequisites: "Charm",
      },
      {
        id: "common-administratum",
        kind: "skill",
        skillId: "common-administratum",
        cost: 100,
      },
      { id: "deceive", kind: "skill", skillId: "deceive", cost: 100 },
      {
        id: "deceive-10",
        kind: "skill",
        skillId: "deceive",
        level: "+10",
        cost: 100,
        prerequisites: "Deceive",
      },
      { id: "disguise", kind: "skill", skillId: "disguise", cost: 100 },
      { id: "dodge", kind: "skill", skillId: "dodge", cost: 100 },
      { id: "evaluate", kind: "skill", skillId: "evaluate", cost: 100 },
      {
        id: "evaluate-10",
        kind: "skill",
        skillId: "evaluate",
        level: "+10",
        cost: 100,
        prerequisites: "Evaluate",
      },
      { id: "inquiry", kind: "skill", skillId: "inquiry", cost: 100 },
      {
        id: "inquiry-10",
        kind: "skill",
        skillId: "inquiry",
        level: "+10",
        cost: 100,
        prerequisites: "Inquiry",
      },
      { id: "medicae", kind: "skill", skillId: "medicae", cost: 100 },
      {
        id: "scholastic-heraldry",
        kind: "skill",
        skillId: "scholastic-heraldry",
        cost: 100,
      },
      {
        id: "scholastic-legend",
        kind: "skill",
        skillId: "scholastic-legend",
        cost: 100,
      },
      {
        id: "scholastic-mercantile",
        kind: "skill",
        skillId: "scholastic-mercantile",
        cost: 100,
      },
      {
        id: "scholastic-philosophy",
        kind: "skill",
        skillId: "scholastic-philosophy",
        cost: 100,
      },
      { id: "scrutiny", kind: "skill", skillId: "scrutiny", cost: 100 },
      { id: "survival", kind: "skill", skillId: "survival", cost: 100 },
      {
        id: "sound-constitution",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 100,
      },
      {
        id: "talented-barter",
        kind: "talent",
        talentId: "talented",
        specialisation: "Barter",
        cost: 100,
        prerequisites: "Barter",
      },
      {
        id: "talented-deceive",
        kind: "talent",
        talentId: "talented",
        specialisation: "Deceive",
        cost: 100,
        prerequisites: "Deceive",
      },
      {
        id: "barter-20",
        kind: "skill",
        skillId: "barter",
        level: "+20",
        cost: 200,
        prerequisites: "Barter +10",
      },
      { id: "carouse", kind: "skill", skillId: "carouse", cost: 200 },
      {
        id: "carouse-10",
        kind: "skill",
        skillId: "carouse",
        level: "+10",
        cost: 200,
        prerequisites: "Carouse",
      },
      {
        id: "common-underworld",
        kind: "skill",
        skillId: "common-underworld",
        cost: 200,
      },
      {
        id: "deceive-20",
        kind: "skill",
        skillId: "deceive",
        level: "+20",
        cost: 200,
        prerequisites: "Deceive +10",
      },
      {
        id: "forbidden-inquisition",
        kind: "skill",
        skillId: "forbidden-inquisition",
        cost: 200,
      },
      {
        id: "forbidden-mutants",
        kind: "skill",
        skillId: "forbidden-mutants",
        cost: 200,
      },
      {
        id: "forbidden-xenos",
        kind: "skill",
        skillId: "forbidden-xenos",
        cost: 200,
      },
      {
        id: "inquiry-20",
        kind: "skill",
        skillId: "inquiry",
        level: "+20",
        cost: 200,
        prerequisites: "Inquiry +10",
      },
      {
        id: "scholastic-mercantile-10",
        kind: "skill",
        skillId: "scholastic-mercantile",
        level: "+10",
        cost: 200,
        prerequisites: "Scholastic Lore (Mercantile)",
      },
      {
        id: "scrutiny-10",
        kind: "skill",
        skillId: "scrutiny",
        level: "+10",
        cost: 200,
        prerequisites: "Scrutiny",
      },
      { id: "tech-use", kind: "skill", skillId: "tech-use", cost: 200 },
      {
        id: "decadence",
        kind: "talent",
        talentId: "decadence",
        cost: 200,
        prerequisites: "T 30",
      },
      { id: "quick-draw", kind: "talent", talentId: "quick-draw", cost: 200 },
      {
        id: "forbidden-archeotech",
        kind: "skill",
        skillId: "forbidden-archeotech",
        cost: 300,
      },
      {
        id: "sleight-of-hand",
        kind: "skill",
        skillId: "sleight-of-hand",
        cost: 300,
      },
      {
        id: "peer-noble",
        kind: "talent",
        talentId: "peer",
        specialisation: "Noble",
        cost: 300,
        prerequisites: "Fel 30",
      },
      {
        id: "peer-underworld",
        kind: "talent",
        talentId: "peer",
        specialisation: "Underworld",
        cost: 300,
        prerequisites: "Fel 30",
      },
    ],
  },
  {
    id: "calixian-xeno-arcanist",
    name: "Calixian Xeno-Arcanist",
    source: SkillSource.IH,
    quote:
      "Yes, you were right to call me in Lord Marshal. The runic symbols are indeed of xeno-origin, yes the dying ones… but the inscription is not in their usual form… this rune here, for example, does indicate a warning, but not against trespass as one might expect but… oh… I say… ahem, I must consult some texts, erm, off world, very important—if my passage could be arranged quickly… perhaps now?",
    attribution: "Xeno-Arcanist Xoth Lyncarte, Prior to the loss of expedition: Seedworld-Gamma-9.",
    description:
      "Becoming a Xeno-Arcanist is more a matter of inclination and opportunity than anything else. Conceivably any adept in the service of the Inquisition could be tasked or driven to study the alien, particularly if, in the past, they have encountered the xenos themselves or acted as curator for xeno-lore or artefacts. This is particularly the case of adepts in the service of Inquisitors from Ordo Xenos, for whom the pursuit of the alien and the destruction of those who have truck with their works is their central quest.",
    requiredCareerIds: ["adept"],
    minimumRank: 4,
    minimumXp: 2_000,
    requirements: {
      minimumIntelligence: 40,
    },
    advances: [
      {
        id: "awareness-20",
        kind: "skill",
        skillId: "awareness",
        level: "+20",
        cost: 100,
        prerequisites: "Awareness +10",
      },
      { id: "deceive", kind: "skill", skillId: "deceive", cost: 100 },
      { id: "dodge", kind: "skill", skillId: "dodge", cost: 100 },
      {
        id: "forbidden-mutants",
        kind: "skill",
        skillId: "forbidden-mutants",
        cost: 100,
      },
      {
        id: "forbidden-inquisition",
        kind: "skill",
        skillId: "forbidden-inquisition",
        cost: 100,
      },
      {
        id: "forbidden-xenos",
        kind: "skill",
        skillId: "forbidden-xenos",
        cost: 100,
      },
      {
        id: "inquiry-10",
        kind: "skill",
        skillId: "inquiry",
        level: "+10",
        cost: 100,
        prerequisites: "Inquiry",
      },
      { id: "medicae", kind: "skill", skillId: "medicae", cost: 100 },
      {
        id: "sound-constitution",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 100,
      },
      { id: "carouse", kind: "skill", skillId: "carouse", cost: 200 },
      {
        id: "carouse-10",
        kind: "skill",
        skillId: "carouse",
        level: "+10",
        cost: 200,
        prerequisites: "Carouse",
      },
      {
        id: "forbidden-xenos-10",
        kind: "skill",
        skillId: "forbidden-xenos",
        level: "+10",
        cost: 200,
        prerequisites: "Forbidden Lore (Xenos)",
      },
      {
        id: "navigation-stellar-10",
        kind: "skill",
        skillId: "navigation-stellar",
        level: "+10",
        cost: 200,
        prerequisites: "Navigation (Stellar)",
      },
      {
        id: "scholastic-cryptology",
        kind: "skill",
        skillId: "scholastic-cryptology",
        cost: 200,
      },
      { id: "tech-use", kind: "skill", skillId: "tech-use", cost: 200 },
      {
        id: "decadence",
        kind: "talent",
        talentId: "decadence",
        cost: 200,
        prerequisites: "T 30",
      },
      {
        id: "heightened-senses-sight",
        kind: "talent",
        talentId: "heightened-senses",
        specialisation: "Sight",
        cost: 200,
      },
      {
        id: "pistol-training-needle",
        kind: "talent",
        talentId: "exotic-weapon-training",
        specialisation: "Needle Pistol",
        cost: 200,
      },
      {
        id: "talented-forbidden-xenos",
        kind: "talent",
        talentId: "talented",
        specialisation: "Forbidden Lore (Xenos)",
        cost: 200,
        prerequisites: "Forbidden Lore (Xenos)",
      },
      { id: "charm", kind: "skill", skillId: "charm", cost: 300 },
      {
        id: "pilot-spacecraft",
        kind: "skill",
        skillId: "pilot-spacecraft",
        cost: 300,
      },
      {
        id: "sleight-of-hand",
        kind: "skill",
        skillId: "sleight-of-hand",
        cost: 300,
      },
      {
        id: "peer-ordo-xenos",
        kind: "talent",
        talentId: "peer",
        specialisation: "Ordo Xenos",
        cost: 300,
        prerequisites: "Fel 30",
      },
      {
        id: "secret-tongue-xenos",
        kind: "skill",
        skillId: "secret-tongue-xenos",
        cost: 400,
        repeatable: true,
      },
    ],
  },
  {
    id: "chaliced-commissariat-operative",
    name: "Chaliced Commissariat Operative",
    source: SkillSource.IH,
    quote: "They have nothing to fear—unless they have something to fear.",
    attribution: "Common saying amongst the Chaliced Commissariat.",
    description: "",
    requiredCareerIds: ["guardsman"],
    minimumRank: 3,
    minimumXp: 1_000,
    requirements: {},
    grantedTraits: ["feared-and-loathed"],
    advances: [
      {
        id: "interrogation",
        kind: "skill",
        skillId: "interrogation",
        cost: 100,
      },
      { id: "intimidate", kind: "skill", skillId: "intimidate", cost: 100 },
      { id: "scrutiny", kind: "skill", skillId: "scrutiny", cost: 100 },
      { id: "search", kind: "skill", skillId: "search", cost: 100 },
      { id: "security", kind: "skill", skillId: "security", cost: 100 },
      {
        id: "melee-shock",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Shock",
        cost: 100,
      },
      {
        id: "street-fighting",
        kind: "talent",
        talentId: "street-fighting",
        cost: 100,
      },
      {
        id: "common-imperium",
        kind: "skill",
        skillId: "common-imperium",
        cost: 200,
      },
      {
        id: "intimidate-10",
        kind: "skill",
        skillId: "intimidate",
        level: "+10",
        cost: 200,
        prerequisites: "Intimidate",
      },
      {
        id: "interrogation-10",
        kind: "skill",
        skillId: "interrogation",
        level: "+10",
        cost: 200,
        prerequisites: "Interrogation",
      },
      {
        id: "air-of-authority",
        kind: "talent",
        talentId: "air-of-authority",
        cost: 200,
        prerequisites: "Fel 30",
      },
      { id: "jaded", kind: "talent", talentId: "jaded", cost: 200 },
      {
        id: "common-underworld",
        kind: "skill",
        skillId: "common-underworld",
        cost: 300,
      },
      {
        id: "interrogation-20",
        kind: "skill",
        skillId: "interrogation",
        level: "+20",
        cost: 300,
        prerequisites: "Interrogation +10",
      },
      {
        id: "intimidate-20",
        kind: "skill",
        skillId: "intimidate",
        level: "+20",
        cost: 300,
        prerequisites: "Intimidate +10",
      },
      { id: "literacy", kind: "skill", skillId: "literacy", cost: 300 },
    ],
  },
  {
    id: "feral-warrior",
    name: "Feral Warrior",
    source: SkillSource.IH,
    quote: "I know not what they will do to the enemy, but by the God-Emperor they terrify me!",
    attribution: "Lord Luther Kronus, on the Mortressan Sythewind Regiment.",
    description: "",
    requiredCareerIds: ["guardsman"],
    minimumRank: 3,
    minimumXp: 1_000,
    requirements: {
      requiredOriginOrTraining: "Feral World",
    },
    advances: [
      {
        id: "awareness-10",
        kind: "skill",
        skillId: "awareness",
        level: "+10",
        cost: 100,
        prerequisites: "Awareness",
      },
      { id: "concealment", kind: "skill", skillId: "concealment", cost: 100 },
      {
        id: "dodge-10",
        kind: "skill",
        skillId: "dodge",
        level: "+10",
        cost: 100,
        prerequisites: "Dodge",
      },
      { id: "intimidate", kind: "skill", skillId: "intimidate", cost: 100 },
      {
        id: "navigation-surface",
        kind: "skill",
        skillId: "navigation-surface",
        cost: 100,
      },
      { id: "silent-move", kind: "skill", skillId: "silent-move", cost: 100 },
      {
        id: "survival-10",
        kind: "skill",
        skillId: "survival",
        level: "+10",
        cost: 100,
        prerequisites: "Survival",
      },
      { id: "wrangling", kind: "skill", skillId: "wrangling", cost: 100 },
      {
        id: "crippling-strike",
        kind: "talent",
        talentId: "crippling-strike",
        cost: 100,
        prerequisites: "WS 50",
      },
      {
        id: "resistance-fear",
        kind: "talent",
        talentId: "resistance",
        specialisation: "Fear",
        cost: 100,
      },
      {
        id: "sound-constitution-1",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 100,
      },
      {
        id: "sound-constitution-2",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 100,
      },
      { id: "gamble", kind: "skill", skillId: "gamble", cost: 200 },
      {
        id: "survival-20",
        kind: "skill",
        skillId: "survival",
        level: "+20",
        cost: 200,
        prerequisites: "Survival +10",
      },
      {
        id: "ambidextrous",
        kind: "talent",
        talentId: "ambidextrous",
        cost: 200,
        prerequisites: "Ag 30",
      },
      {
        id: "die-hard",
        kind: "talent",
        talentId: "die-hard",
        cost: 200,
        prerequisites: "WP 40",
      },
      { id: "frenzy", kind: "talent", talentId: "frenzy", cost: 200 },
      {
        id: "melee-chain",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Chain",
        cost: 200,
      },
      {
        id: "swift-attack",
        kind: "talent",
        talentId: "swift-attack",
        cost: 200,
        prerequisites: "WS 35",
      },
      {
        id: "beast-hunter",
        kind: "talent",
        talentId: "beast-hunter",
        cost: 200,
        prerequisites: "WS 35, BS 35",
      },
    ],
  },
  {
    id: "legate-investigator",
    name: "Legate Investigator",
    source: SkillSource.IH,
    quote:
      "Did you receive the heretics into your company? Did you swear to them any service? Did you, knowing that they are the foulest of traitors, aid them by deliberate act, by tolerating their presence, or by the sin of silence when knowing of heresy?",
    attribution: "From the Blessed Rituals of Inquiry, Volume IX.",
    description: "",
    requiredCareerIds: ["adept", "arbitrator", "cleric", "guardsman", "imperial-psyker"],
    minimumRank: 4,
    minimumXp: 2_000,
    requirements: {
      requiredSkills: ["literacy"],
      requiresInquisitorOffer: true,
    },
    grantedGear: [
      {
        id: "legature",
        referenceId: "ih-legature",
        name: "Legature",
        description:
          "A formal carta of inquiry stating the locale of investigation and the focus of concern. On presentation and corroboration of a Sigil of Inquiry, it grants the bearer the absolute right to question and examine whoever or whatever they wish.",
      },
      {
        id: "sigil-of-question",
        referenceId: "ih-sigil-of-question",
        name: "Sigil of Question",
        description:
          "A silver icon featuring the sign of a chalice engraved with the symbol of the Inquisition. It demonstrates the Legate Investigator’s remit and authority under the Ordos Calixis. It may be worn as a medallion, carried in a wallet or worn on a finger as a ring, and contains a code-key system for verification and secure data-access if needed.",
      },
    ],
    advances: [
      { id: "command", kind: "skill", skillId: "command", cost: 100 },
      {
        id: "forbidden-cults",
        kind: "skill",
        skillId: "forbidden-cults",
        cost: 100,
      },
      {
        id: "forbidden-heresy",
        kind: "skill",
        skillId: "forbidden-heresy",
        cost: 100,
      },
      {
        id: "forbidden-mutants",
        kind: "skill",
        skillId: "forbidden-mutants",
        cost: 100,
      },
      {
        id: "forbidden-psyker",
        kind: "skill",
        skillId: "forbidden-psyker",
        cost: 100,
      },
      { id: "inquiry", kind: "skill", skillId: "inquiry", cost: 100 },
      {
        id: "inquiry-10",
        kind: "skill",
        skillId: "inquiry",
        level: "+10",
        cost: 100,
        prerequisites: "Inquiry",
      },
      {
        id: "interrogation",
        kind: "skill",
        skillId: "interrogation",
        cost: 100,
      },
      {
        id: "interrogation-10",
        kind: "skill",
        skillId: "interrogation",
        level: "+10",
        cost: 100,
        prerequisites: "Interrogate",
      },
      { id: "scrutiny", kind: "skill", skillId: "scrutiny", cost: 100 },
      {
        id: "scrutiny-10",
        kind: "skill",
        skillId: "scrutiny",
        level: "+10",
        cost: 100,
        prerequisites: "Scrutiny",
      },
      {
        id: "ciphers-inquisition",
        kind: "skill",
        skillId: "ciphers-inquisition",
        cost: 200,
      },
      {
        id: "forbidden-cults-10",
        kind: "skill",
        skillId: "forbidden-cults",
        level: "+10",
        cost: 200,
        prerequisites: "Forbidden Lore (Cults)",
      },
      {
        id: "forbidden-heresy-10",
        kind: "skill",
        skillId: "forbidden-heresy",
        level: "+10",
        cost: 200,
        prerequisites: "Forbidden Lore (Heresy)",
      },
      {
        id: "forbidden-mutants-10",
        kind: "skill",
        skillId: "forbidden-mutants",
        level: "+10",
        cost: 200,
        prerequisites: "Forbidden Lore (Mutants)",
      },
      {
        id: "forbidden-psyker-10",
        kind: "skill",
        skillId: "forbidden-psyker",
        level: "+10",
        cost: 200,
        prerequisites: "Forbidden Lore (Psykers)",
      },
      {
        id: "inquiry-20",
        kind: "skill",
        skillId: "inquiry",
        level: "+20",
        cost: 200,
        prerequisites: "Inquiry +10",
      },
      {
        id: "interrogation-20",
        kind: "skill",
        skillId: "interrogation",
        level: "+20",
        cost: 200,
        prerequisites: "Interrogate +10",
      },
      {
        id: "scholastic-judgement",
        kind: "skill",
        skillId: "scholastic-judgement",
        cost: 200,
      },
      {
        id: "scrutiny-20",
        kind: "skill",
        skillId: "scrutiny",
        level: "+20",
        cost: 200,
        prerequisites: "Scrutiny +10",
      },
      {
        id: "air-of-authority",
        kind: "talent",
        talentId: "air-of-authority",
        cost: 200,
        prerequisites: "Fel 30",
      },
      {
        id: "talented-inquiry",
        kind: "talent",
        talentId: "talented",
        specialisation: "Inquiry",
        cost: 200,
        prerequisites: "Inquiry",
      },
      {
        id: "talented-interrogation",
        kind: "talent",
        talentId: "talented",
        specialisation: "Interrogation",
        cost: 200,
        prerequisites: "Interrogation",
      },
    ],
  },
  {
    id: "malfian-bloodsworn",
    name: "Malfian Bloodsworn",
    source: SkillSource.IH,
    quote:
      "Now be a nice gent and come here and bleed on this warrant for me, eh? Then I’ll make it quick for ye, otherwise I’ll get a bit put out, and well… I hate swabbing the floor and getting nice parchment dirty. Seems so… undignified like.",
    attribution: "Auric Kenge, Chartered Bloodsworn.",
    description:
      "A holder of a Bloodsworn Charter has certain rights above those of a common hired gun. The warrant enables them to bear arms in the hive where others would not, access legal record, enter private dwellings, and even avoid interference from local enforcers and armsmen in pursuit of their warrants. These powers have limits and do not extend to the holdings or persons of the Adepta or Malfi’s rulers.",
    requiredCareerIds: ["assassin", "scum", "guardsman", "arbitrator"],
    minimumRank: 5,
    minimumXp: 3_000,
    requirements: {
      otherRequirements: [
        "Guardsmen or Arbitrators must no longer be in overt Imperial service.",
        "Must gain a charter from the Blood Guild of Malfi.",
      ],
    },
    grantedEliteAdvances: ["bloodsworn-charter"],
    advances: [
      { id: "charm", kind: "skill", skillId: "charm", cost: 100 },
      {
        id: "common-administratum",
        kind: "skill",
        skillId: "common-administratum",
        cost: 100,
      },
      { id: "deceive", kind: "skill", skillId: "deceive", cost: 100 },
      { id: "inquiry", kind: "skill", skillId: "inquiry", cost: 100 },
      {
        id: "inquiry-10",
        kind: "skill",
        skillId: "inquiry",
        level: "+10",
        cost: 100,
        prerequisites: "Inquiry",
      },
      {
        id: "inquiry-20",
        kind: "skill",
        skillId: "inquiry",
        level: "+20",
        cost: 100,
        prerequisites: "Inquiry +10",
      },
      { id: "interrogation", kind: "skill", skillId: "interrogation", cost: 100 },
      {
        id: "interrogation-10",
        kind: "skill",
        skillId: "interrogation",
        level: "+10",
        cost: 100,
        prerequisites: "Interrogation",
      },
      { id: "search", kind: "skill", skillId: "search", cost: 100 },
      {
        id: "search-10",
        kind: "skill",
        skillId: "search",
        level: "+10",
        cost: 100,
        prerequisites: "Search",
      },
      { id: "security", kind: "skill", skillId: "security", cost: 100 },
      {
        id: "security-10",
        kind: "skill",
        skillId: "security",
        level: "+10",
        cost: 100,
        prerequisites: "Security",
      },
      { id: "shadowing", kind: "skill", skillId: "shadowing", cost: 100 },
      {
        id: "shadowing-10",
        kind: "skill",
        skillId: "shadowing",
        level: "+10",
        cost: 100,
        prerequisites: "Shadowing",
      },
      { id: "survival", kind: "skill", skillId: "survival", cost: 100 },
      { id: "tracking", kind: "skill", skillId: "tracking", cost: 100 },
      {
        id: "tracking-10",
        kind: "skill",
        skillId: "tracking",
        level: "+10",
        cost: 100,
        prerequisites: "Tracking",
      },
      {
        id: "basic-bolt",
        kind: "talent",
        talentId: "basic-weapon-training",
        specialisation: "Bolt",
        cost: 100,
      },
      {
        id: "decadence",
        kind: "talent",
        talentId: "decadence",
        cost: 100,
        prerequisites: "T 30",
      },
      {
        id: "hard-target",
        kind: "talent",
        talentId: "hard-target",
        cost: 100,
        prerequisites: "Ag 40",
      },
      {
        id: "heightened-senses-hearing",
        kind: "talent",
        talentId: "heightened-senses",
        specialisation: "Hearing",
        cost: 100,
      },
      {
        id: "heightened-senses-sight",
        kind: "talent",
        talentId: "heightened-senses",
        specialisation: "Sight",
        cost: 100,
      },
      {
        id: "iron-jaw",
        kind: "talent",
        talentId: "iron-jaw",
        cost: 100,
        prerequisites: "T 40",
      },
      {
        id: "jaded",
        kind: "talent",
        talentId: "jaded",
        cost: 100,
        prerequisites: "WP 30",
      },
      {
        id: "peer-underworld",
        kind: "talent",
        talentId: "peer",
        specialisation: "Underworld",
        cost: 100,
        prerequisites: "Fel 30",
      },
      {
        id: "pistol-bolt",
        kind: "talent",
        talentId: "pistol-training",
        specialisation: "Bolt",
        cost: 100,
      },
      {
        id: "rapid-reaction",
        kind: "talent",
        talentId: "rapid-reaction",
        cost: 100,
        prerequisites: "Ag 40",
      },
      {
        id: "street-fighting",
        kind: "talent",
        talentId: "street-fighting",
        cost: 100,
      },
      { id: "barter", kind: "skill", skillId: "barter", cost: 200 },
      { id: "carouse", kind: "skill", skillId: "carouse", cost: 200 },
      { id: "evaluate", kind: "skill", skillId: "evaluate", cost: 200 },
      {
        id: "forbidden-mutants",
        kind: "skill",
        skillId: "forbidden-mutants",
        cost: 200,
      },
      {
        id: "nerves-of-steel",
        kind: "talent",
        talentId: "nerves-of-steel",
        cost: 200,
      },
      { id: "paranoia", kind: "talent", talentId: "paranoia", cost: 200 },
      {
        id: "sound-constitution-1",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 200,
      },
      {
        id: "sound-constitution-2",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 200,
      },
      {
        id: "talented-inquiry",
        kind: "talent",
        talentId: "talented",
        specialisation: "Inquiry",
        cost: 200,
        prerequisites: "Inquiry",
      },
      {
        id: "two-weapon-wielder-ballistic",
        kind: "talent",
        talentId: "two-weapon-wielder",
        specialisation: "Ballistic",
        cost: 300,
        prerequisites: "BS 35, Ag 35",
      },
      {
        id: "two-weapon-wielder-melee",
        kind: "talent",
        talentId: "two-weapon-wielder",
        specialisation: "Melee",
        cost: 300,
        prerequisites: "WS 35, Ag 35",
      },
    ],
  },
  {
    id: "mechanicus-secutor",
    name: "Mechanicus Secutor",
    source: SkillSource.IH,
    quote:
      "…++CORPUS FINIS+MACHINA MAGNUS+SANCTUS METALLUM+POTESTAS OMNISSIAH, OMNISSIAH VULT+DEATH TO THE ENEMIES OF THE MACHINE GOD++CORPUS FIN…",
    attribution:
      "Repeating transmission, overwhelming all signal channels. The annihilation of House Caloclast, Hive Tarsus.",
    requiredCareerIds: ["tech-priest"],
    minimumRank: 4,
    minimumXp: 2_000,
    requirements: {
      otherRequirements: ["WS 35", "BS 35", "WP 35", "Any four Weapon Training talents"],
    },
    advances: [
      { id: "command", kind: "skill", skillId: "command", cost: 100 },
      {
        id: "common-machine-cult-20",
        kind: "skill",
        skillId: "common-machine-cult",
        level: "+20",
        cost: 100,
        prerequisites: "Common Lore (Machine Cult) +10",
      },
      { id: "common-war", kind: "skill", skillId: "common-war", cost: 100 },
      {
        id: "common-war-10",
        kind: "skill",
        skillId: "common-war",
        level: "+10",
        cost: 100,
        prerequisites: "Common Lore (War)",
      },
      { id: "ciphers-myrmidon", kind: "skill", skillId: "ciphers-myrmidon", cost: 100 },
      {
        id: "ciphers-myrmidon-10",
        kind: "skill",
        skillId: "ciphers-myrmidon",
        level: "+10",
        cost: 100,
        prerequisites: "Ciphers (Myrmidon)",
      },
      {
        id: "demolition-10",
        kind: "skill",
        skillId: "demolition",
        level: "+10",
        cost: 100,
        prerequisites: "Demolition",
      },
      {
        id: "drive-hover-10",
        kind: "skill",
        skillId: "drive-hover",
        level: "+10",
        cost: 100,
        prerequisites: "Drive (Hover Vehicle)",
      },
      {
        id: "drive-walker-20",
        kind: "skill",
        skillId: "drive-walker",
        level: "+20",
        cost: 100,
        prerequisites: "Drive (Walker) +10",
      },
      { id: "intimidate", kind: "skill", skillId: "intimidate", cost: 100 },
      { id: "navigation-surface", kind: "skill", skillId: "navigation-surface", cost: 100 },
      { id: "pilot-military", kind: "skill", skillId: "pilot-military", cost: 100 },
      {
        id: "ambidextrous",
        kind: "talent",
        talentId: "ambidextrous",
        cost: 100,
        prerequisites: "Ag 30",
      },
      {
        id: "basic-bolt",
        kind: "talent",
        talentId: "basic-weapon-training",
        specialisation: "Bolt",
        cost: 100,
      },
      {
        id: "basic-flame",
        kind: "talent",
        talentId: "basic-weapon-training",
        specialisation: "Flame",
        cost: 100,
      },
      {
        id: "basic-melta",
        kind: "talent",
        talentId: "basic-weapon-training",
        specialisation: "Melta",
        cost: 100,
      },
      { id: "concealed-cavity", kind: "talent", talentId: "concealed-cavity", cost: 100 },
      {
        id: "crippling-strike",
        kind: "talent",
        talentId: "crippling-strike",
        cost: 100,
        prerequisites: "WS 50",
      },
      { id: "ferric-lure", kind: "talent", talentId: "ferric-lure", cost: 100 },
      {
        id: "heavy-sp",
        kind: "talent",
        talentId: "heavy-weapon-training",
        specialisation: "SP",
        cost: 100,
      },
      {
        id: "mechadendrite-manipulator",
        kind: "talent",
        talentId: "mechadendrite-use",
        specialisation: "Manipulator",
        cost: 100,
        prerequisites: "Tech-Priest",
      },
      {
        id: "mechadendrite-optical",
        kind: "talent",
        talentId: "mechadendrite-use",
        specialisation: "Optical",
        cost: 100,
        prerequisites: "Tech-Priest",
      },
      {
        id: "melee-chain",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Chain",
        cost: 100,
      },
      {
        id: "pistol-flame",
        kind: "talent",
        talentId: "pistol-training",
        specialisation: "Flame",
        cost: 100,
      },
      {
        id: "pistol-plasma",
        kind: "talent",
        talentId: "pistol-training",
        specialisation: "Plasma",
        cost: 100,
      },
      {
        id: "resistance-cold",
        kind: "talent",
        talentId: "resistance",
        specialisation: "Cold",
        cost: 100,
      },
      {
        id: "resistance-heat",
        kind: "talent",
        talentId: "resistance",
        specialisation: "Heat",
        cost: 100,
      },
      {
        id: "resistance-poisons",
        kind: "talent",
        talentId: "resistance",
        specialisation: "Poisons",
        cost: 100,
      },
      { id: "sound-constitution-100-1", kind: "talent", talentId: "sound-constitution", cost: 100 },
      { id: "sound-constitution-100-2", kind: "talent", talentId: "sound-constitution", cost: 100 },
      {
        id: "total-recall",
        kind: "talent",
        talentId: "total-recall",
        cost: 100,
        prerequisites: "Int 30",
      },
      { id: "awareness", kind: "skill", skillId: "awareness", cost: 200 },
      {
        id: "ciphers-myrmidon-20",
        kind: "skill",
        skillId: "ciphers-myrmidon",
        level: "+20",
        cost: 200,
        prerequisites: "Ciphers (Myrmidon) +10",
      },
      {
        id: "command-10",
        kind: "skill",
        skillId: "command",
        level: "+10",
        cost: 200,
        prerequisites: "Command",
      },
      { id: "common-guard", kind: "skill", skillId: "common-guard", cost: 200 },
      {
        id: "secret-tongue-acolyte-10",
        kind: "skill",
        skillId: "secret-tongue-acolyte",
        level: "+10",
        cost: 200,
        prerequisites: "Secret Tongue (Acolyte)",
      },
      {
        id: "bulging-biceps",
        kind: "talent",
        talentId: "bulging-biceps",
        cost: 200,
        prerequisites: "S 45",
      },
      {
        id: "exotic-breacher",
        kind: "talent",
        talentId: "exotic-weapon-training",
        specialisation: "Breacher",
        cost: 200,
      },
      {
        id: "exotic-shock-blaster",
        kind: "talent",
        talentId: "exotic-weapon-training",
        specialisation: "Shock Blaster",
        cost: 200,
      },
      {
        id: "hatred-tech-heretics",
        kind: "talent",
        talentId: "hatred",
        specialisation: "Tech Heretics",
        cost: 200,
      },
      { id: "hatred-xeno", kind: "talent", talentId: "hatred", specialisation: "Xeno", cost: 200 },
      {
        id: "heavy-las",
        kind: "talent",
        talentId: "heavy-weapon-training",
        specialisation: "Las",
        cost: 200,
      },
      {
        id: "heavy-launcher",
        kind: "talent",
        talentId: "heavy-weapon-training",
        specialisation: "Launcher",
        cost: 200,
      },
      {
        id: "mechadendrite-gun",
        kind: "talent",
        talentId: "mechadendrite-use",
        specialisation: "Gun",
        cost: 200,
        prerequisites: "Tech-Priest",
      },
      {
        id: "melee-power",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Power",
        cost: 200,
      },
      {
        id: "resistance-fear",
        kind: "talent",
        talentId: "resistance",
        specialisation: "Fear",
        cost: 200,
      },
      {
        id: "resistance-psychic-powers",
        kind: "talent",
        talentId: "resistance",
        specialisation: "Psychic Powers",
        cost: 200,
      },
      { id: "sound-constitution-200-1", kind: "talent", talentId: "sound-constitution", cost: 200 },
      { id: "sound-constitution-200-2", kind: "talent", talentId: "sound-constitution", cost: 200 },
      {
        id: "two-weapon-wielder-ballistic",
        kind: "talent",
        talentId: "two-weapon-wielder",
        specialisation: "Ballistic",
        cost: 200,
        prerequisites: "BS 35, Ag 35",
      },
      {
        id: "two-weapon-wielder-melee",
        kind: "talent",
        talentId: "two-weapon-wielder",
        specialisation: "Melee",
        cost: 200,
        prerequisites: "WS 35, Ag 35",
      },
      { id: "forbidden-archeotech", kind: "skill", skillId: "forbidden-archeotech", cost: 300 },
      { id: "forbidden-xenos", kind: "skill", skillId: "forbidden-xenos", cost: 300 },
      { id: "forbidden-warp", kind: "skill", skillId: "forbidden-warp", cost: 300 },
      { id: "die-hard", kind: "talent", talentId: "die-hard", cost: 300, prerequisites: "WP 40" },
      {
        id: "exotic-graviton-gun",
        kind: "talent",
        talentId: "exotic-weapon-training",
        specialisation: "Graviton Gun",
        cost: 300,
      },
      {
        id: "exotic-needle-pistol",
        kind: "talent",
        talentId: "exotic-weapon-training",
        specialisation: "Needle Pistol",
        cost: 300,
      },
      {
        id: "exotic-rad-cleanser",
        kind: "talent",
        talentId: "exotic-weapon-training",
        specialisation: "Rad-Cleanser",
        cost: 300,
      },
      {
        id: "machinator-array",
        kind: "talent",
        talentId: "machinator-array",
        cost: 500,
        prerequisites: "Tech-Priest, Mechadendrite Use (Gun)",
      },
    ],
  },
  {
    id: "metallican-gunslinger",
    name: "Metallican Gunslinger",
    source: SkillSource.IH,
    quote:
      "They say he’s fast, like chain lightning fast. I don’t believe ’em, no one’s that fast.",
    attribution: "Last words attributed to Kail Strom, bounty hunter, deceased.",
    description:
      "This Rank 1 Alternate Rank may be selected at character creation as the character’s Advance Scheme. It does not alter the Career’s starting Skills or Talents, only how and on what the character may spend starting XP.",
    requiredCareerIds: ["assassin", "scum"],
    minimumRank: 1,
    minimumXp: 0,
    requirements: {
      minimumBallisticSkill: 30,
      requiredOriginOrTraining: "Gunmetal City",
    },
    availableAtCharacterCreation: true,
    grantedTraits: ["knave-of-pistols"],
    advances: [
      { id: "dodge", kind: "skill", skillId: "dodge", cost: 100 },
      {
        id: "ambidextrous",
        kind: "talent",
        talentId: "ambidextrous",
        cost: 100,
        prerequisites: "Ag 30",
      },
      {
        id: "blind-fighting",
        kind: "talent",
        talentId: "blind-fighting",
        cost: 100,
        prerequisites: "Per 30",
      },
      {
        id: "crack-shot",
        kind: "talent",
        talentId: "crack-shot",
        cost: 100,
        prerequisites: "BS 40",
      },
      {
        id: "nerves-of-steel",
        kind: "talent",
        talentId: "nerves-of-steel",
        cost: 100,
      },
      {
        id: "rapid-reaction",
        kind: "talent",
        talentId: "rapid-reaction",
        cost: 100,
        prerequisites: "Ag 40",
      },
      { id: "rapid-reload", kind: "talent", talentId: "rapid-reload", cost: 100 },
      {
        id: "two-weapon-wielder-ballistic",
        kind: "talent",
        talentId: "two-weapon-wielder",
        specialisation: "Ballistic",
        cost: 100,
        prerequisites: "BS 35, Ag 35",
      },
      {
        id: "sleight-of-hand",
        kind: "skill",
        skillId: "sleight-of-hand",
        cost: 200,
      },
      {
        id: "deadeye-shot",
        kind: "talent",
        talentId: "deadeye-shot",
        cost: 200,
        prerequisites: "BS 30",
      },
      {
        id: "independent-targeting",
        kind: "talent",
        talentId: "independent-targeting",
        cost: 200,
        prerequisites: "BS 40",
      },
      {
        id: "lightning-reflexes",
        kind: "talent",
        talentId: "lightning-reflexes",
        cost: 200,
      },
      {
        id: "mighty-shot",
        kind: "talent",
        talentId: "mighty-shot",
        cost: 200,
        prerequisites: "BS 40",
      },
      {
        id: "pistol-bolt",
        kind: "talent",
        talentId: "pistol-training",
        specialisation: "Bolt",
        cost: 200,
      },
      {
        id: "dual-shot",
        kind: "talent",
        talentId: "dual-shot",
        cost: 300,
        prerequisites: "Ag 40, Two-Weapon Wielder (Ballistic)",
      },
      {
        id: "gunslinger",
        kind: "talent",
        talentId: "gunslinger",
        cost: 300,
        prerequisites: "BS 40, Two-Weapon Wielder (Ballistic)",
      },
      {
        id: "hip-shooting",
        kind: "talent",
        talentId: "hip-shooting",
        cost: 300,
        prerequisites: "BS 40, Ag 40",
      },
      {
        id: "jaded",
        kind: "talent",
        talentId: "jaded",
        cost: 300,
        prerequisites: "WP 30",
      },
    ],
  },
  {
    id: "moritat-reaper",
    name: "Moritat Reaper",
    source: SkillSource.IH,
    quote:
      "I never saw the killer fully, though I thank the Saviour-Emperor for her. We’d lost half the squad and Proctor Alelradd had just gone down with his throat bit open. I fired off the last round from my Puritan and had nothing left but my boot knife and a prayer on my lips when this dark shape dropped from the gantry above. The carriondantes, well, the rotted things just came apart, black clotted blood and rancid flesh everywhere. The one in front of me went down in five twitching chunks and I swear I didn’t see a single sword stroke fall… a miracle sir. The Emperor’s own bloody work, like a death angel from the old hive tales.",
    attribution: "Deputy Provost Morcar, Report on the Morningside Incident, Hive Gloriana.",
    description:
      "To become a Moritat Reaper, you must have been created with the option of the Moritat Assassin Background Package. This Career choice is designed to be a culmination of that Origin and choice. Over the course of your adventures, you must also stay true to the Moritat’s dogma and defeat several of the cult’s favoured enemies in single combat with the edge of the blade.",
    requiredCareerIds: ["assassin"],
    minimumRank: 6,
    minimumXp: 6_000,
    requirements: {
      otherRequirements: [
        "Moritat Assassin Background Package",
        "Remain true to the Moritat Death Cult’s code",
      ],
    },
    advances: [
      {
        id: "climb-20",
        kind: "skill",
        skillId: "climb",
        level: "+20",
        cost: 100,
        prerequisites: "Climb +10",
      },
      {
        id: "concealment-10",
        kind: "skill",
        skillId: "concealment",
        level: "+10",
        cost: 100,
        prerequisites: "Concealment",
      },
      {
        id: "contortionist-10",
        kind: "skill",
        skillId: "contortionist",
        level: "+10",
        cost: 100,
        prerequisites: "Contortionist",
      },
      { id: "deceive", kind: "skill", skillId: "deceive", cost: 100 },
      {
        id: "intimidate-10",
        kind: "skill",
        skillId: "intimidate",
        level: "+10",
        cost: 100,
        prerequisites: "Intimidate",
      },
      { id: "meditation", kind: "talent", talentId: "meditation", cost: 100 },
      {
        id: "secret-tongue-moritat-10",
        kind: "skill",
        skillId: "secret-tongue-moritat",
        level: "+10",
        cost: 100,
        prerequisites: "Secret Tongue (Moritat)",
      },
      {
        id: "silent-move-20",
        kind: "skill",
        skillId: "silent-move",
        level: "+20",
        cost: 100,
        prerequisites: "Silent Move +10",
      },
      {
        id: "survival-10",
        kind: "skill",
        skillId: "survival",
        level: "+10",
        cost: 100,
        prerequisites: "Survival",
      },
      {
        id: "ambidextrous",
        kind: "talent",
        talentId: "ambidextrous",
        cost: 100,
        prerequisites: "Ag 30",
      },
      {
        id: "assassin-strike",
        kind: "talent",
        talentId: "assassin-strike",
        cost: 100,
        prerequisites: "Ag 40, Acrobatics",
      },
      {
        id: "combat-master",
        kind: "talent",
        talentId: "combat-master",
        cost: 100,
        prerequisites: "WS 30",
      },
      {
        id: "deceive-10",
        kind: "skill",
        skillId: "deceive",
        level: "+10",
        cost: 200,
        prerequisites: "Deceive",
      },
      { id: "forbidden-cults", kind: "skill", skillId: "forbidden-cults", cost: 200 },
      {
        id: "scholastic-legend",
        kind: "skill",
        skillId: "scholastic-legend",
        cost: 200,
      },
      {
        id: "scholastic-occult",
        kind: "skill",
        skillId: "scholastic-occult",
        cost: 200,
      },
      {
        id: "secret-tongue-moritat-20",
        kind: "skill",
        skillId: "secret-tongue-moritat",
        level: "+20",
        cost: 200,
        prerequisites: "Secret Tongue (Moritat) +10",
      },
      {
        id: "counter-attack",
        kind: "talent",
        talentId: "counter-attack",
        cost: 200,
        prerequisites: "WS 40",
      },
      {
        id: "dual-strike",
        kind: "talent",
        talentId: "dual-strike",
        cost: 200,
        prerequisites: "Ag 40, Two-Weapon Wielder (Melee)",
      },
      { id: "frenzy", kind: "talent", talentId: "frenzy", cost: 200 },
      {
        id: "hatred-heretics",
        kind: "talent",
        talentId: "hatred",
        specialisation: "Heretics",
        cost: 200,
      },
      {
        id: "hatred-mutants",
        kind: "talent",
        talentId: "hatred",
        specialisation: "Mutants",
        cost: 200,
      },
      {
        id: "hatred-psykers",
        kind: "talent",
        talentId: "hatred",
        specialisation: "Psykers",
        cost: 200,
      },
      {
        id: "insanely-faithful",
        kind: "talent",
        talentId: "insanely-faithful",
        cost: 200,
      },
      {
        id: "nerves-of-steel",
        kind: "talent",
        talentId: "nerves-of-steel",
        cost: 200,
      },
      { id: "sound-constitution-1", kind: "talent", talentId: "sound-constitution", cost: 200 },
      { id: "sound-constitution-2", kind: "talent", talentId: "sound-constitution", cost: 200 },
      { id: "sound-constitution-3", kind: "talent", talentId: "sound-constitution", cost: 200 },
      {
        id: "step-aside",
        kind: "talent",
        talentId: "step-aside",
        cost: 200,
        prerequisites: "Ag 40, Dodge",
      },
      {
        id: "wall-of-steel",
        kind: "talent",
        talentId: "wall-of-steel",
        cost: 200,
        prerequisites: "Ag 35",
      },
      {
        id: "peer-inquisition",
        kind: "talent",
        talentId: "peer",
        specialisation: "Inquisition",
        cost: 300,
        prerequisites: "Fel 30",
      },
      {
        id: "the-reaping",
        kind: "talent",
        talentId: "the-reaping",
        cost: 300,
        prerequisites: "WS 40, Combat Master",
      },
    ],
  },
  {
    id: "reclamator",
    name: "Reclamator",
    source: SkillSource.IH,
    quote:
      "Tranters, primes, ’lthic cells, hand rippers, I can get ’em all, reconditioned and good as new—even a batch of good slaught. Great wheel o’ the steel god crush me if it’s not so… The price? Let’s not quibble about the price. You see, I know this up-hive guilder rolling in gelt and he needs a little intel you may have the knowing of yourself…",
    attribution: "Obadiah Plex, Hive Magnogorsk Reclamator.",
    description:
      "This Rank 1 Alternate Rank may be selected at character creation as the character’s Advance Scheme. It does not alter the Career’s starting Skills or Talents, only how and on what the character may spend starting XP.",
    requiredCareerIds: ["scum"],
    minimumRank: 1,
    minimumXp: 0,
    requirements: {
      minimumIntelligence: 30,
      requiredOriginOrTraining: "Hive World, Forge World, or Void Born",
    },
    availableAtCharacterCreation: true,
    advances: [
      {
        id: "awareness-10",
        kind: "skill",
        skillId: "awareness",
        level: "+10",
        cost: 100,
        prerequisites: "Awareness",
      },
      { id: "barter", kind: "skill", skillId: "barter", cost: 100 },
      { id: "charm", kind: "skill", skillId: "charm", cost: 100 },
      { id: "dodge", kind: "skill", skillId: "dodge", cost: 100 },
      {
        id: "dodge-10",
        kind: "skill",
        skillId: "dodge",
        level: "+10",
        cost: 100,
        prerequisites: "Dodge",
      },
      { id: "drive-ground", kind: "skill", skillId: "drive-ground", cost: 100 },
      { id: "evaluate", kind: "skill", skillId: "evaluate", cost: 100 },
      { id: "search", kind: "skill", skillId: "search", cost: 100 },
      { id: "trade-technomat", kind: "skill", skillId: "trade-technomat", cost: 100 },
      {
        id: "trade-technomat-10",
        kind: "skill",
        skillId: "trade-technomat",
        level: "+10",
        cost: 100,
        prerequisites: "Trade (Technomat)",
      },
      {
        id: "pistol-las",
        kind: "talent",
        talentId: "pistol-training",
        specialisation: "Las",
        cost: 100,
      },
      {
        id: "pistol-primitive",
        kind: "talent",
        talentId: "pistol-training",
        specialisation: "Primitive",
        cost: 100,
      },
      { id: "unremarkable", kind: "talent", talentId: "unremarkable", cost: 100 },
      { id: "sound-constitution-1", kind: "talent", talentId: "sound-constitution", cost: 100 },
      { id: "sound-constitution-2", kind: "talent", talentId: "sound-constitution", cost: 100 },
      {
        id: "barter-10",
        kind: "skill",
        skillId: "barter",
        level: "+10",
        cost: 200,
        prerequisites: "Barter",
      },
      { id: "chem-use", kind: "skill", skillId: "chem-use", cost: 200 },
      { id: "common-tech", kind: "skill", skillId: "common-tech", cost: 200 },
      { id: "tech-use", kind: "skill", skillId: "tech-use", cost: 200 },
      { id: "quick-draw", kind: "talent", talentId: "quick-draw", cost: 200 },
      {
        id: "common-machine-cult",
        kind: "skill",
        skillId: "common-machine-cult",
        cost: 300,
      },
      {
        id: "scholastic-chymistry",
        kind: "skill",
        skillId: "scholastic-chymistry",
        cost: 300,
      },
      {
        id: "tech-use-10",
        kind: "skill",
        skillId: "tech-use",
        level: "+10",
        cost: 300,
        prerequisites: "Tech Use",
      },
    ],
  },
  {
    id: "warden-divisio-immoralis",
    name: "Warden of the Divisio Immoralis",
    source: SkillSource.IH,
    quote:
      "Sleep well tonight. Dream the sweetest of dreams and remember their careless touch. For it will be the last peaceful sleep you will ever have.",
    attribution: "Address to newly inducted Wardens by Senior Arbiter Kae Drusil.",
    description:
      "This Rank 1 Alternate Rank may be selected during character creation. It does not affect the character’s starting Skills or Talents, only where they can invest their starting XP.",
    requiredCareerIds: ["arbitrator"],
    minimumRank: 1,
    minimumXp: 0,
    requirements: {},
    availableAtCharacterCreation: true,
    insanityGain: "1d5",
    advances: [
      { id: "awareness", kind: "skill", skillId: "awareness", cost: 100 },
      {
        id: "common-arbites-10",
        kind: "skill",
        skillId: "common-arbites",
        level: "+10",
        cost: 100,
        prerequisites: "Common Lore (Adeptus Arbites)",
      },
      { id: "drive-ground", kind: "skill", skillId: "drive-ground", cost: 100 },
      { id: "drive-hover", kind: "skill", skillId: "drive-hover", cost: 100 },
      { id: "forbidden-cults", kind: "skill", skillId: "forbidden-cults", cost: 100 },
      {
        id: "inquiry-10",
        kind: "skill",
        skillId: "inquiry",
        level: "+10",
        cost: 100,
        prerequisites: "Inquiry",
      },
      { id: "scrutiny", kind: "skill", skillId: "scrutiny", cost: 100 },
      {
        id: "armour-of-contempt",
        kind: "talent",
        talentId: "armour-of-contempt",
        cost: 100,
        prerequisites: "WP 40",
      },
      {
        id: "basic-sp",
        kind: "talent",
        talentId: "basic-weapon-training",
        specialisation: "SP",
        cost: 100,
      },
      {
        id: "decadence",
        kind: "talent",
        talentId: "decadence",
        cost: 100,
        prerequisites: "T 30",
      },
      {
        id: "melee-primitive",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Primitive",
        cost: 100,
      },
      {
        id: "peer-the-insane",
        kind: "talent",
        talentId: "peer",
        specialisation: "The Insane",
        cost: 100,
        prerequisites: "Fel 30",
      },
      {
        id: "pistol-sp",
        kind: "talent",
        talentId: "pistol-training",
        specialisation: "SP",
        cost: 100,
      },
      { id: "sound-constitution", kind: "talent", talentId: "sound-constitution", cost: 100 },
      {
        id: "resistance-fear",
        kind: "talent",
        talentId: "resistance",
        specialisation: "Fear",
        cost: 100,
      },
      {
        id: "forbidden-cults-10",
        kind: "skill",
        skillId: "forbidden-cults",
        level: "+10",
        cost: 200,
        prerequisites: "Forbidden Lore (Cults)",
      },
      { id: "forbidden-heresy", kind: "skill", skillId: "forbidden-heresy", cost: 200 },
      {
        id: "scholastic-occult",
        kind: "skill",
        skillId: "scholastic-occult",
        cost: 200,
      },
      { id: "flagellant", kind: "talent", talentId: "flagellant", cost: 200 },
    ],
  },
  {
    id: "tyrantine-shadow-agent",
    name: "Tyrantine Shadow Agent",
    source: SkillSource.IH,
    quote: "Lest the truth devour all.",
    attribution: "Memento Mori on the Tomb of Inquisitor Cassilda Cognos.",
    requiredCareerIds: [
      "adept",
      "arbitrator",
      "assassin",
      "cleric",
      "guardsman",
      "imperial-psyker",
      "scum",
    ],
    minimumRank: 5,
    minimumXp: 3_000,
    requirements: {},
    advances: [
      {
        id: "ciphers-tenebrae-collegium",
        kind: "skill",
        skillId: "ciphers-tenebrae-collegium",
        cost: 100,
      },
      {
        id: "ciphers-tenebrae-collegium-10",
        kind: "skill",
        skillId: "ciphers-tenebrae-collegium",
        level: "+10",
        cost: 100,
        prerequisites: "Ciphers (Tenebrae Collegium)",
      },
      {
        id: "ciphers-tenebrae-collegium-20",
        kind: "skill",
        skillId: "ciphers-tenebrae-collegium",
        level: "+20",
        cost: 100,
        prerequisites: "Ciphers (Tenebrae Collegium) +10",
      },
      { id: "deceive", kind: "skill", skillId: "deceive", cost: 100 },
      {
        id: "deceive-10",
        kind: "skill",
        skillId: "deceive",
        level: "+10",
        cost: 100,
        prerequisites: "Deceive",
      },
      { id: "disguise", kind: "skill", skillId: "disguise", cost: 100 },
      {
        id: "disguise-10",
        kind: "skill",
        skillId: "disguise",
        level: "+10",
        cost: 100,
        prerequisites: "Disguise",
      },
      { id: "inquiry", kind: "skill", skillId: "inquiry", cost: 100 },
      {
        id: "scholastic-legend",
        kind: "skill",
        skillId: "scholastic-legend",
        cost: 100,
      },
      {
        id: "secret-tongue-tenebrae-collegium",
        kind: "skill",
        skillId: "secret-tongue-tenebrae-collegium",
        cost: 100,
      },
      {
        id: "secret-tongue-tenebrae-collegium-10",
        kind: "skill",
        skillId: "secret-tongue-tenebrae-collegium",
        level: "+10",
        cost: 100,
        prerequisites: "Secret Tongue (Tenebrae Collegium)",
      },
      {
        id: "secret-tongue-tenebrae-collegium-20",
        kind: "skill",
        skillId: "secret-tongue-tenebrae-collegium",
        level: "+20",
        cost: 100,
        prerequisites: "Secret Tongue (Tenebrae Collegium) +10",
      },
      {
        id: "labyrinth-conditioning",
        kind: "talent",
        talentId: "labyrinth-conditioning",
        cost: 100,
        prerequisites: "Int 30",
      },
      { id: "mimic", kind: "talent", talentId: "mimic", cost: 100 },
      {
        id: "resistance-psychic-powers",
        kind: "talent",
        talentId: "resistance",
        specialisation: "Psychic Powers",
        cost: 100,
      },
      { id: "unremarkable", kind: "talent", talentId: "unremarkable", cost: 100 },
      {
        id: "deceive-20",
        kind: "skill",
        skillId: "deceive",
        level: "+20",
        cost: 200,
        prerequisites: "Deceive +10",
      },
      {
        id: "disguise-20",
        kind: "skill",
        skillId: "disguise",
        level: "+20",
        cost: 200,
        prerequisites: "Disguise +10",
      },
      { id: "forbidden-cults", kind: "skill", skillId: "forbidden-cults", cost: 200 },
      {
        id: "forbidden-cults-10",
        kind: "skill",
        skillId: "forbidden-cults",
        level: "+10",
        cost: 200,
        prerequisites: "Forbidden Lore (Cults)",
      },
      {
        id: "forbidden-inquisition",
        kind: "skill",
        skillId: "forbidden-inquisition",
        cost: 200,
      },
      {
        id: "forbidden-inquisition-10",
        kind: "skill",
        skillId: "forbidden-inquisition",
        level: "+10",
        cost: 200,
        prerequisites: "Forbidden Lore (the Inquisition)",
      },
      {
        id: "inquiry-10",
        kind: "skill",
        skillId: "inquiry",
        level: "+10",
        cost: 200,
        prerequisites: "Inquiry",
      },
      {
        id: "inquiry-20",
        kind: "skill",
        skillId: "inquiry",
        level: "+20",
        cost: 200,
        prerequisites: "Inquiry +10",
      },
      {
        id: "scholastic-legend-10",
        kind: "skill",
        skillId: "scholastic-legend",
        level: "+10",
        cost: 200,
        prerequisites: "Scholastic Lore (Legend)",
      },
      {
        id: "strong-minded",
        kind: "talent",
        talentId: "strong-minded",
        cost: 200,
        prerequisites: "WP 30, Resistance (Psychic)",
      },
      {
        id: "mental-fortress",
        kind: "talent",
        talentId: "mental-fortress",
        cost: 300,
        prerequisites: "WP 50, Strong Minded",
      },
    ],
  },
  {
    id: "templar-calix",
    name: "Templar Calix of the Scholastia Psykana",
    source: SkillSource.IH,
    quote:
      "Will and blade, life and death, cause and consequence, mind and matter, soul’s truth and warp’s lie: all things indivisible and one.",
    attribution: "Temple Calix Training Mantra.",
    description:
      "During their training, a Templar Calix must help construct or obtain a force weapon of their own, which may result in a small scenario for the Player Character at the GM’s discretion.",
    requiredCareerIds: ["imperial-psyker"],
    requiredCareerPaths: ["Savant Militant"],
    minimumRank: 4,
    minimumXp: 2_000,
    requirements: {
      maximumInsanity: 10,
      maximumCorruption: 10,
    },
    grantedMeleeWeaponChoice: {
      id: "force-weapon",
      label: "Force weapon",
      referenceIds: ["ih-force-axe", "ih-force-staff", "ih-force-sword"],
    },
    characteristicAdvanceOverrides: {
      ws: { simple: 100, intermediate: 250, trained: 500, expert: 750 },
      int: { simple: 500, intermediate: 750, trained: 1_000, expert: 2_500 },
    },
    advances: [
      { id: "acrobatics", kind: "skill", skillId: "acrobatics", cost: 100 },
      {
        id: "acrobatics-10",
        kind: "skill",
        skillId: "acrobatics",
        level: "+10",
        cost: 100,
        prerequisites: "Acrobatics",
      },
      {
        id: "dodge-10",
        kind: "skill",
        skillId: "dodge",
        level: "+10",
        cost: 100,
        prerequisites: "Dodge",
      },
      { id: "meditation", kind: "talent", talentId: "meditation", cost: 100 },
      {
        id: "psyniscience-10",
        kind: "skill",
        skillId: "psyniscience",
        level: "+10",
        cost: 100,
        prerequisites: "Psyniscience",
      },
      {
        id: "secret-tongue-temple-calix",
        kind: "skill",
        skillId: "secret-tongue-temple-calix",
        cost: 100,
      },
      {
        id: "secret-tongue-temple-calix-10",
        kind: "skill",
        skillId: "secret-tongue-temple-calix",
        level: "+10",
        cost: 100,
        prerequisites: "Secret Tongue (Temple Calix)",
      },
      {
        id: "secret-tongue-temple-calix-20",
        kind: "skill",
        skillId: "secret-tongue-temple-calix",
        level: "+20",
        cost: 100,
        prerequisites: "Secret Tongue (Temple Calix) +10",
      },
      {
        id: "ambidextrous",
        kind: "talent",
        talentId: "ambidextrous",
        cost: 100,
        prerequisites: "Ag 30",
      },
      {
        id: "armour-of-contempt",
        kind: "talent",
        talentId: "armour-of-contempt",
        cost: 100,
        prerequisites: "WP 40",
      },
      {
        id: "blademaster",
        kind: "talent",
        talentId: "blademaster",
        cost: 100,
        prerequisites: "WS 35, Melee Weapon Training (any)",
      },
      {
        id: "blind-fighting",
        kind: "talent",
        talentId: "blind-fighting",
        cost: 100,
        prerequisites: "Per 30",
      },
      { id: "catfall", kind: "talent", talentId: "catfall", cost: 100, prerequisites: "Ag 30" },
      {
        id: "corpus-conversion",
        kind: "talent",
        talentId: "corpus-conversion",
        cost: 100,
        prerequisites: "Psy Rating 2",
      },
      {
        id: "deflect-shot",
        kind: "talent",
        talentId: "deflect-shot",
        cost: 100,
        prerequisites: "Ag 50",
      },
      { id: "disarm", kind: "talent", talentId: "disarm", cost: 100, prerequisites: "Ag 30" },
      {
        id: "crippling-strike",
        kind: "talent",
        talentId: "crippling-strike",
        cost: 100,
        prerequisites: "WS 50",
      },
      {
        id: "crushing-blow",
        kind: "talent",
        talentId: "crushing-blow",
        cost: 100,
        prerequisites: "S 40",
      },
      {
        id: "hard-target",
        kind: "talent",
        talentId: "hard-target",
        cost: 100,
        prerequisites: "Ag 40",
      },
      {
        id: "melee-chain",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Chain",
        cost: 100,
      },
      {
        id: "melee-power",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Power",
        cost: 100,
      },
      {
        id: "minor-psychic-power-1",
        kind: "talent",
        talentId: "minor-psychic-power",
        cost: 100,
      },
      {
        id: "minor-psychic-power-2",
        kind: "talent",
        talentId: "minor-psychic-power",
        cost: 100,
      },
      {
        id: "precise-blow",
        kind: "talent",
        talentId: "precise-blow",
        cost: 100,
        prerequisites: "WS 30, Sure Strike",
      },
      {
        id: "resistance-fear",
        kind: "talent",
        talentId: "resistance",
        specialisation: "Fear",
        cost: 100,
      },
      { id: "sound-constitution-100", kind: "talent", talentId: "sound-constitution", cost: 100 },
      { id: "street-fighting", kind: "talent", talentId: "street-fighting", cost: 100 },
      {
        id: "sure-strike",
        kind: "talent",
        talentId: "sure-strike",
        cost: 100,
        prerequisites: "WS 30",
      },
      {
        id: "two-weapon-wielder-melee",
        kind: "talent",
        talentId: "two-weapon-wielder",
        specialisation: "Melee",
        cost: 100,
        prerequisites: "WS 35",
      },
      {
        id: "acrobatics-20",
        kind: "skill",
        skillId: "acrobatics",
        level: "+20",
        cost: 200,
        prerequisites: "Acrobatics +10",
      },
      {
        id: "dodge-20",
        kind: "skill",
        skillId: "dodge",
        level: "+20",
        cost: 200,
        prerequisites: "Dodge +10",
      },
      {
        id: "combat-master",
        kind: "talent",
        talentId: "combat-master",
        cost: 200,
        prerequisites: "WS 30",
      },
      {
        id: "counter-attack",
        kind: "talent",
        talentId: "counter-attack",
        cost: 200,
        prerequisites: "WS 40",
      },
      {
        id: "discipline-focus",
        kind: "talent",
        talentId: "discipline-focus",
        cost: 200,
        prerequisites: "Psy Rating 3",
      },
      {
        id: "dual-strike",
        kind: "talent",
        talentId: "dual-strike",
        cost: 200,
        prerequisites: "Ag 40, Two-Weapon Wielder (Melee)",
      },
      { id: "jaded", kind: "talent", talentId: "jaded", cost: 200 },
      { id: "lightning-reflexes", kind: "talent", talentId: "lightning-reflexes", cost: 200 },
      { id: "sound-constitution-200", kind: "talent", talentId: "sound-constitution", cost: 200 },
      {
        id: "swift-attack",
        kind: "talent",
        talentId: "swift-attack",
        cost: 200,
        prerequisites: "WS 35",
      },
      {
        id: "psy-rating-3",
        kind: "talent",
        talentId: "psy-rating-3",
        cost: 200,
        prerequisites: "Psy Rating 2",
      },
      { id: "psychic-power-1", kind: "talent", talentId: "psychic-power", cost: 200 },
      { id: "psychic-power-2", kind: "talent", talentId: "psychic-power", cost: 200 },
      {
        id: "forbidden-psyker-10",
        kind: "skill",
        skillId: "forbidden-psyker",
        level: "+10",
        cost: 300,
        prerequisites: "Forbidden Lore (Psykers)",
      },
      {
        id: "assassin-strike",
        kind: "talent",
        talentId: "assassin-strike",
        cost: 300,
        prerequisites: "Ag 40, Acrobatics",
      },
      {
        id: "lightning-attack",
        kind: "talent",
        talentId: "lightning-attack",
        cost: 300,
        prerequisites: "Swift Attack",
      },
      {
        id: "peer-noble",
        kind: "talent",
        talentId: "peer",
        specialisation: "Noble",
        cost: 300,
      },
      {
        id: "psy-rating-4",
        kind: "talent",
        talentId: "psy-rating-4",
        cost: 300,
        prerequisites: "Psy Rating 3",
      },
      { id: "sound-constitution-300", kind: "talent", talentId: "sound-constitution", cost: 300 },
      {
        id: "step-aside",
        kind: "talent",
        talentId: "step-aside",
        cost: 300,
        prerequisites: "Ag 40, Dodge",
      },
      {
        id: "wall-of-steel",
        kind: "talent",
        talentId: "wall-of-steel",
        cost: 300,
        prerequisites: "Ag 35",
      },
    ],
  },
  {
    id: "sister-oblatia",
    name: "Sister Oblatia",
    source: SkillSource.IH,
    quote: "If I must die, I shall welcome Death as an old friend, and wrap mine arms around it.",
    attribution: "Oath of the Penitent.",
    requiredCareerIds: ["adepta-sororitas"],
    minimumRank: 5,
    minimumXp: 3_000,
    requirements: {},
    advances: [
      { id: "concealment", kind: "skill", skillId: "concealment", cost: 100 },
      { id: "inquiry", kind: "skill", skillId: "inquiry", cost: 100 },
      { id: "interrogation", kind: "skill", skillId: "interrogation", cost: 100 },
      { id: "intimidate", kind: "skill", skillId: "intimidate", cost: 100 },
      { id: "silent-move", kind: "skill", skillId: "silent-move", cost: 100 },
      { id: "ambidextrous", kind: "talent", talentId: "ambidextrous", cost: 100 },
      {
        id: "blind-fighting",
        kind: "talent",
        talentId: "blind-fighting",
        cost: 100,
        prerequisites: "Per 30",
      },
      {
        id: "melee-chain",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Chain",
        cost: 100,
      },
      {
        id: "melee-power",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Power",
        cost: 100,
      },
      {
        id: "melee-shock",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Shock",
        cost: 100,
      },
      { id: "sound-constitution-1", kind: "talent", talentId: "sound-constitution", cost: 100 },
      { id: "sound-constitution-2", kind: "talent", talentId: "sound-constitution", cost: 100 },
      {
        id: "two-weapon-wielder-melee",
        kind: "talent",
        talentId: "two-weapon-wielder",
        specialisation: "Melee",
        cost: 100,
        prerequisites: "WS 35, Ag 35",
      },
      {
        id: "two-weapon-wielder-ballistic",
        kind: "talent",
        talentId: "two-weapon-wielder",
        specialisation: "Ballistic",
        cost: 100,
        prerequisites: "BS 35, Ag 35",
      },
      {
        id: "dodge-20",
        kind: "skill",
        skillId: "dodge",
        level: "+20",
        cost: 200,
        prerequisites: "Dodge +10",
      },
      { id: "scholastic-occult", kind: "skill", skillId: "scholastic-occult", cost: 200 },
      { id: "tracking", kind: "skill", skillId: "tracking", cost: 200 },
      {
        id: "crushing-blow",
        kind: "talent",
        talentId: "crushing-blow",
        cost: 200,
        prerequisites: "S 40",
      },
      {
        id: "die-hard",
        kind: "talent",
        talentId: "die-hard",
        cost: 200,
        prerequisites: "WP 40",
      },
      { id: "frenzy", kind: "talent", talentId: "frenzy", cost: 200 },
      {
        id: "furious-assault",
        kind: "talent",
        talentId: "furious-assault",
        cost: 200,
        prerequisites: "WS 35",
      },
      {
        id: "lightning-reflexes",
        kind: "talent",
        talentId: "lightning-reflexes",
        cost: 200,
        prerequisites: "Ag 30",
      },
      { id: "rapid-reload", kind: "talent", talentId: "rapid-reload", cost: 200 },
      {
        id: "swift-attack",
        kind: "talent",
        talentId: "swift-attack",
        cost: 200,
        prerequisites: "WS 35",
      },
      { id: "forbidden-heresy", kind: "skill", skillId: "forbidden-heresy", cost: 300 },
      { id: "forbidden-cults", kind: "skill", skillId: "forbidden-cults", cost: 300 },
      {
        id: "duty-unto-death",
        kind: "talent",
        talentId: "duty-unto-death",
        cost: 300,
        prerequisites: "WP 45",
      },
      { id: "fearless", kind: "talent", talentId: "fearless", cost: 300 },
    ],
  },
];
