import type { SkillAdvanceLevel } from "./types.js";
import { SkillSource } from "./skillSource.js";

export interface AlternateRankSkillAdvance {
  id: string;
  kind: "skill";
  skillId: string;
  level?: Exclude<SkillAdvanceLevel, "untrained">;
  cost: number;
  prerequisites?: string;
  repeatable?: boolean;
}

export interface AlternateRankTalentAdvance {
  id: string;
  kind: "talent";
  talentId: string;
  specialisation?: string;
  cost: number;
  prerequisites?: string;
}

export interface AlternateRankEliteAdvance {
  id: string;
  kind: "elite-advance";
  eliteAdvanceId: string;
}

export type AlternateRankAdvance =
  | AlternateRankSkillAdvance
  | AlternateRankTalentAdvance
  | AlternateRankEliteAdvance;

export interface AlternateRankGearGrant {
  id: string;
  referenceId: string;
  name: string;
  description: string;
}

export interface AlternateRankData {
  id: string;
  name: string;
  source: SkillSource;
  quote: string;
  attribution: string;
  description: string;
  requiredCareerIds: readonly string[];
  minimumRank: number;
  minimumXp: number;
  requirements: {
    maximumCorruption?: number;
    minimumIntelligence?: number;
    minimumFellowship?: number;
    requiredSkills?: readonly string[];
    requiresInquisitorOffer?: boolean;
    requiredOriginOrTraining?: string;
    excludedOrigins?: readonly string[];
    otherRequirements?: readonly string[];
  };
  grantedTraits?: readonly string[];
  grantedGear?: readonly AlternateRankGearGrant[];
  grantedEliteAdvances?: readonly string[];
  advances: readonly AlternateRankAdvance[];
}

export const ALTERNATE_RANKS: readonly AlternateRankData[] = [
  {
    id: "black-priest-of-maccabeus",
    name: "Black Priest of Maccabeus",
    source: SkillSource.IH,
    quote:
      "I walk in the footsteps of the Blessed Saint Drusus and I go about the Emperor’s work. At my word the unclean spirit baulks and the heretic withers in shame. Who, then, are you to stand against me?",
    attribution: "Prior Cornelius Agrippa, Maccabean Exorcist.",
    description:
      "In order to qualify for this path, the character must be a Cleric who either originates from Maccabeus Quintus, or with the permission (or at the behest) of their Inquisitorial masters is sent to train there during ‘downtime’ between adventures. This Career Path is particularly suited to Clerics who want a more directly combative role against the powers of the warp, or who in their character’s past have survived encounters with the Daemonic.",
    requiredCareerIds: ["cleric"],
    minimumRank: 4,
    minimumXp: 2_000,
    requirements: {
      maximumCorruption: 9,
      requiredOriginOrTraining: "Maccabeus Quintus",
      excludedOrigins: ["Mind Cleansed"],
    },
    advances: [
      { id: "command", kind: "skill", skillId: "command", cost: 100 },
      {
        id: "common-imperial-creed-20",
        kind: "skill",
        skillId: "common-imperial-creed",
        level: "+20",
        cost: 100,
        prerequisites: "Common Lore (Imperial Creed) +10",
      },
      {
        id: "deceive-10",
        kind: "skill",
        skillId: "deceive",
        level: "+10",
        cost: 100,
        prerequisites: "Deceive",
      },
      { id: "forbidden-cults", kind: "skill", skillId: "forbidden-cults", cost: 100 },
      {
        id: "forbidden-daemonology",
        kind: "skill",
        skillId: "forbidden-daemonology",
        cost: 100,
      },
      {
        id: "forbidden-daemonology-10",
        kind: "skill",
        skillId: "forbidden-daemonology",
        level: "+10",
        cost: 100,
        prerequisites: "Forbidden Lore (Daemonology)",
      },
      { id: "interrogation", kind: "skill", skillId: "interrogation", cost: 100 },
      { id: "intimidation", kind: "skill", skillId: "intimidate", cost: 100 },
      {
        id: "pilot-civilian-10",
        kind: "skill",
        skillId: "pilot-civilian",
        level: "+10",
        cost: 100,
        prerequisites: "Pilot (Civilian Craft)",
      },
      {
        id: "scholastic-legend-10",
        kind: "skill",
        skillId: "scholastic-legend",
        level: "+10",
        cost: 100,
        prerequisites: "Scholastic Lore (Legend)",
      },
      {
        id: "scholastic-occult",
        kind: "skill",
        skillId: "scholastic-occult",
        cost: 100,
      },
      {
        id: "speak-high-gothic",
        kind: "skill",
        skillId: "speak-high-gothic",
        cost: 100,
      },
      {
        id: "basic-bolt",
        kind: "talent",
        talentId: "basic-weapon-training",
        specialisation: "Bolt",
        cost: 100,
      },
      {
        id: "basic-flame",
        kind: "talent",
        talentId: "basic-weapon-training",
        specialisation: "Flame",
        cost: 100,
      },
      {
        id: "hatred-daemons",
        kind: "talent",
        talentId: "hatred",
        specialisation: "Daemons",
        cost: 100,
      },
      {
        id: "master-orator",
        kind: "talent",
        talentId: "master-orator",
        cost: 100,
        prerequisites: "Fel 30",
      },
      {
        id: "melee-chain",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Chain",
        cost: 100,
      },
      {
        id: "unshakeable-faith",
        kind: "talent",
        talentId: "unshakeable-faith",
        cost: 100,
      },
      {
        id: "sound-constitution-100",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 100,
      },
      {
        id: "command-10",
        kind: "skill",
        skillId: "command",
        level: "+10",
        cost: 200,
        prerequisites: "Command",
      },
      {
        id: "forbidden-cults-10",
        kind: "skill",
        skillId: "forbidden-cults",
        level: "+10",
        cost: 200,
        prerequisites: "Forbidden Lore (Cults)",
      },
      { id: "forbidden-warp", kind: "skill", skillId: "forbidden-warp", cost: 200 },
      {
        id: "melee-power",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Power",
        cost: 200,
      },
      {
        id: "peer-ordo-malleus",
        kind: "talent",
        talentId: "peer",
        specialisation: "Ordo Malleus",
        cost: 200,
        prerequisites: "Fel 30",
      },
      {
        id: "pistol-bolt",
        kind: "talent",
        talentId: "pistol-training",
        specialisation: "Bolt",
        cost: 200,
      },
      {
        id: "pistol-flame",
        kind: "talent",
        talentId: "pistol-training",
        specialisation: "Flame",
        cost: 200,
      },
      {
        id: "sound-constitution-200",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 200,
      },
      { id: "pure-faith", kind: "talent", talentId: "pure-faith", cost: 300 },
      {
        id: "purge-the-unclean",
        kind: "talent",
        talentId: "purge-the-unclean",
        cost: 300,
        prerequisites: "Pure Faith",
      },
      {
        id: "encarta-maleficarum",
        kind: "elite-advance",
        eliteAdvanceId: "encarta-maleficarum",
      },
    ],
  },
  {
    id: "bonded-emissary",
    name: "Bonded Emissary",
    source: SkillSource.IH,
    quote:
      "My masters regret that your harvest has failed governor and unrest stirs your little world. Perhaps you should seek assistance from the free captains as you did three years ago when you turned down our last generous offer, and with it the protection of our friendship… no? Well, unfortunately things have grown harsher in the sub-sector of late and our price now is regrettably somewhat higher…",
    attribution: "Adept-Assayer Alisha Zhou, Emissary of the Machenko Dynasty.",
    description: "",
    requiredCareerIds: ["adept", "tech-priest"],
    minimumRank: 4,
    minimumXp: 2_000,
    requirements: {
      minimumIntelligence: 30,
      minimumFellowship: 30,
    },
    advances: [
      { id: "barter", kind: "skill", skillId: "barter", cost: 100 },
      {
        id: "barter-10",
        kind: "skill",
        skillId: "barter",
        level: "+10",
        cost: 100,
        prerequisites: "Barter",
      },
      { id: "charm", kind: "skill", skillId: "charm", cost: 100 },
      {
        id: "charm-10",
        kind: "skill",
        skillId: "charm",
        level: "+10",
        cost: 100,
        prerequisites: "Charm",
      },
      {
        id: "common-administratum",
        kind: "skill",
        skillId: "common-administratum",
        cost: 100,
      },
      { id: "deceive", kind: "skill", skillId: "deceive", cost: 100 },
      {
        id: "deceive-10",
        kind: "skill",
        skillId: "deceive",
        level: "+10",
        cost: 100,
        prerequisites: "Deceive",
      },
      { id: "disguise", kind: "skill", skillId: "disguise", cost: 100 },
      { id: "dodge", kind: "skill", skillId: "dodge", cost: 100 },
      { id: "evaluate", kind: "skill", skillId: "evaluate", cost: 100 },
      {
        id: "evaluate-10",
        kind: "skill",
        skillId: "evaluate",
        level: "+10",
        cost: 100,
        prerequisites: "Evaluate",
      },
      { id: "inquiry", kind: "skill", skillId: "inquiry", cost: 100 },
      {
        id: "inquiry-10",
        kind: "skill",
        skillId: "inquiry",
        level: "+10",
        cost: 100,
        prerequisites: "Inquiry",
      },
      { id: "medicae", kind: "skill", skillId: "medicae", cost: 100 },
      {
        id: "scholastic-heraldry",
        kind: "skill",
        skillId: "scholastic-heraldry",
        cost: 100,
      },
      {
        id: "scholastic-legend",
        kind: "skill",
        skillId: "scholastic-legend",
        cost: 100,
      },
      {
        id: "scholastic-mercantile",
        kind: "skill",
        skillId: "scholastic-mercantile",
        cost: 100,
      },
      {
        id: "scholastic-philosophy",
        kind: "skill",
        skillId: "scholastic-philosophy",
        cost: 100,
      },
      { id: "scrutiny", kind: "skill", skillId: "scrutiny", cost: 100 },
      { id: "survival", kind: "skill", skillId: "survival", cost: 100 },
      {
        id: "sound-constitution",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 100,
      },
      {
        id: "talented-barter",
        kind: "talent",
        talentId: "talented",
        specialisation: "Barter",
        cost: 100,
        prerequisites: "Barter",
      },
      {
        id: "talented-deceive",
        kind: "talent",
        talentId: "talented",
        specialisation: "Deceive",
        cost: 100,
        prerequisites: "Deceive",
      },
      {
        id: "barter-20",
        kind: "skill",
        skillId: "barter",
        level: "+20",
        cost: 200,
        prerequisites: "Barter +10",
      },
      { id: "carouse", kind: "skill", skillId: "carouse", cost: 200 },
      {
        id: "carouse-10",
        kind: "skill",
        skillId: "carouse",
        level: "+10",
        cost: 200,
        prerequisites: "Carouse",
      },
      {
        id: "common-underworld",
        kind: "skill",
        skillId: "common-underworld",
        cost: 200,
      },
      {
        id: "deceive-20",
        kind: "skill",
        skillId: "deceive",
        level: "+20",
        cost: 200,
        prerequisites: "Deceive +10",
      },
      {
        id: "forbidden-inquisition",
        kind: "skill",
        skillId: "forbidden-inquisition",
        cost: 200,
      },
      {
        id: "forbidden-mutants",
        kind: "skill",
        skillId: "forbidden-mutants",
        cost: 200,
      },
      {
        id: "forbidden-xenos",
        kind: "skill",
        skillId: "forbidden-xenos",
        cost: 200,
      },
      {
        id: "inquiry-20",
        kind: "skill",
        skillId: "inquiry",
        level: "+20",
        cost: 200,
        prerequisites: "Inquiry +10",
      },
      {
        id: "scholastic-mercantile-10",
        kind: "skill",
        skillId: "scholastic-mercantile",
        level: "+10",
        cost: 200,
        prerequisites: "Scholastic Lore (Mercantile)",
      },
      {
        id: "scrutiny-10",
        kind: "skill",
        skillId: "scrutiny",
        level: "+10",
        cost: 200,
        prerequisites: "Scrutiny",
      },
      { id: "tech-use", kind: "skill", skillId: "tech-use", cost: 200 },
      {
        id: "decadence",
        kind: "talent",
        talentId: "decadence",
        cost: 200,
        prerequisites: "T 30",
      },
      { id: "quick-draw", kind: "talent", talentId: "quick-draw", cost: 200 },
      {
        id: "forbidden-archeotech",
        kind: "skill",
        skillId: "forbidden-archeotech",
        cost: 300,
      },
      {
        id: "sleight-of-hand",
        kind: "skill",
        skillId: "sleight-of-hand",
        cost: 300,
      },
      {
        id: "peer-noble",
        kind: "talent",
        talentId: "peer",
        specialisation: "Noble",
        cost: 300,
        prerequisites: "Fel 30",
      },
      {
        id: "peer-underworld",
        kind: "talent",
        talentId: "peer",
        specialisation: "Underworld",
        cost: 300,
        prerequisites: "Fel 30",
      },
    ],
  },
  {
    id: "calixian-xeno-arcanist",
    name: "Calixian Xeno-Arcanist",
    source: SkillSource.IH,
    quote:
      "Yes, you were right to call me in Lord Marshal. The runic symbols are indeed of xeno-origin, yes the dying ones… but the inscription is not in their usual form… this rune here, for example, does indicate a warning, but not against trespass as one might expect but… oh… I say… ahem, I must consult some texts, erm, off world, very important—if my passage could be arranged quickly… perhaps now?",
    attribution: "Xeno-Arcanist Xoth Lyncarte, Prior to the loss of expedition: Seedworld-Gamma-9.",
    description:
      "Becoming a Xeno-Arcanist is more a matter of inclination and opportunity than anything else. Conceivably any adept in the service of the Inquisition could be tasked or driven to study the alien, particularly if, in the past, they have encountered the xenos themselves or acted as curator for xeno-lore or artefacts. This is particularly the case of adepts in the service of Inquisitors from Ordo Xenos, for whom the pursuit of the alien and the destruction of those who have truck with their works is their central quest.",
    requiredCareerIds: ["adept"],
    minimumRank: 4,
    minimumXp: 2_000,
    requirements: {
      minimumIntelligence: 40,
    },
    advances: [
      {
        id: "awareness-20",
        kind: "skill",
        skillId: "awareness",
        level: "+20",
        cost: 100,
        prerequisites: "Awareness +10",
      },
      { id: "deceive", kind: "skill", skillId: "deceive", cost: 100 },
      { id: "dodge", kind: "skill", skillId: "dodge", cost: 100 },
      {
        id: "forbidden-mutants",
        kind: "skill",
        skillId: "forbidden-mutants",
        cost: 100,
      },
      {
        id: "forbidden-inquisition",
        kind: "skill",
        skillId: "forbidden-inquisition",
        cost: 100,
      },
      {
        id: "forbidden-xenos",
        kind: "skill",
        skillId: "forbidden-xenos",
        cost: 100,
      },
      {
        id: "inquiry-10",
        kind: "skill",
        skillId: "inquiry",
        level: "+10",
        cost: 100,
        prerequisites: "Inquiry",
      },
      { id: "medicae", kind: "skill", skillId: "medicae", cost: 100 },
      {
        id: "sound-constitution",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 100,
      },
      { id: "carouse", kind: "skill", skillId: "carouse", cost: 200 },
      {
        id: "carouse-10",
        kind: "skill",
        skillId: "carouse",
        level: "+10",
        cost: 200,
        prerequisites: "Carouse",
      },
      {
        id: "forbidden-xenos-10",
        kind: "skill",
        skillId: "forbidden-xenos",
        level: "+10",
        cost: 200,
        prerequisites: "Forbidden Lore (Xenos)",
      },
      {
        id: "navigation-stellar-10",
        kind: "skill",
        skillId: "navigation-stellar",
        level: "+10",
        cost: 200,
        prerequisites: "Navigation (Stellar)",
      },
      {
        id: "scholastic-cryptology",
        kind: "skill",
        skillId: "scholastic-cryptology",
        cost: 200,
      },
      { id: "tech-use", kind: "skill", skillId: "tech-use", cost: 200 },
      {
        id: "decadence",
        kind: "talent",
        talentId: "decadence",
        cost: 200,
        prerequisites: "T 30",
      },
      {
        id: "heightened-senses-sight",
        kind: "talent",
        talentId: "heightened-senses",
        specialisation: "Sight",
        cost: 200,
      },
      {
        id: "pistol-training-needle",
        kind: "talent",
        talentId: "exotic-weapon-training",
        specialisation: "Needle Pistol",
        cost: 200,
      },
      {
        id: "talented-forbidden-xenos",
        kind: "talent",
        talentId: "talented",
        specialisation: "Forbidden Lore (Xenos)",
        cost: 200,
        prerequisites: "Forbidden Lore (Xenos)",
      },
      { id: "charm", kind: "skill", skillId: "charm", cost: 300 },
      {
        id: "pilot-spacecraft",
        kind: "skill",
        skillId: "pilot-spacecraft",
        cost: 300,
      },
      {
        id: "sleight-of-hand",
        kind: "skill",
        skillId: "sleight-of-hand",
        cost: 300,
      },
      {
        id: "peer-ordo-xenos",
        kind: "talent",
        talentId: "peer",
        specialisation: "Ordo Xenos",
        cost: 300,
        prerequisites: "Fel 30",
      },
      {
        id: "secret-tongue-xenos",
        kind: "skill",
        skillId: "secret-tongue-xenos",
        cost: 400,
        repeatable: true,
      },
    ],
  },
  {
    id: "chaliced-commissariat-operative",
    name: "Chaliced Commissariat Operative",
    source: SkillSource.IH,
    quote: "They have nothing to fear—unless they have something to fear.",
    attribution: "Common saying amongst the Chaliced Commissariat.",
    description: "",
    requiredCareerIds: ["guardsman"],
    minimumRank: 3,
    minimumXp: 1_000,
    requirements: {},
    grantedTraits: ["feared-and-loathed"],
    advances: [
      {
        id: "interrogation",
        kind: "skill",
        skillId: "interrogation",
        cost: 100,
      },
      { id: "intimidate", kind: "skill", skillId: "intimidate", cost: 100 },
      { id: "scrutiny", kind: "skill", skillId: "scrutiny", cost: 100 },
      { id: "search", kind: "skill", skillId: "search", cost: 100 },
      { id: "security", kind: "skill", skillId: "security", cost: 100 },
      {
        id: "melee-shock",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Shock",
        cost: 100,
      },
      {
        id: "street-fighting",
        kind: "talent",
        talentId: "street-fighting",
        cost: 100,
      },
      {
        id: "common-imperium",
        kind: "skill",
        skillId: "common-imperium",
        cost: 200,
      },
      {
        id: "intimidate-10",
        kind: "skill",
        skillId: "intimidate",
        level: "+10",
        cost: 200,
        prerequisites: "Intimidate",
      },
      {
        id: "interrogation-10",
        kind: "skill",
        skillId: "interrogation",
        level: "+10",
        cost: 200,
        prerequisites: "Interrogation",
      },
      {
        id: "air-of-authority",
        kind: "talent",
        talentId: "air-of-authority",
        cost: 200,
        prerequisites: "Fel 30",
      },
      { id: "jaded", kind: "talent", talentId: "jaded", cost: 200 },
      {
        id: "common-underworld",
        kind: "skill",
        skillId: "common-underworld",
        cost: 300,
      },
      {
        id: "interrogation-20",
        kind: "skill",
        skillId: "interrogation",
        level: "+20",
        cost: 300,
        prerequisites: "Interrogation +10",
      },
      {
        id: "intimidate-20",
        kind: "skill",
        skillId: "intimidate",
        level: "+20",
        cost: 300,
        prerequisites: "Intimidate +10",
      },
      { id: "literacy", kind: "skill", skillId: "literacy", cost: 300 },
    ],
  },
  {
    id: "feral-warrior",
    name: "Feral Warrior",
    source: SkillSource.IH,
    quote: "I know not what they will do to the enemy, but by the God-Emperor they terrify me!",
    attribution: "Lord Luther Kronus, on the Mortressan Sythewind Regiment.",
    description: "",
    requiredCareerIds: ["guardsman"],
    minimumRank: 3,
    minimumXp: 1_000,
    requirements: {
      requiredOriginOrTraining: "Feral World",
    },
    advances: [
      {
        id: "awareness-10",
        kind: "skill",
        skillId: "awareness",
        level: "+10",
        cost: 100,
        prerequisites: "Awareness",
      },
      { id: "concealment", kind: "skill", skillId: "concealment", cost: 100 },
      {
        id: "dodge-10",
        kind: "skill",
        skillId: "dodge",
        level: "+10",
        cost: 100,
        prerequisites: "Dodge",
      },
      { id: "intimidate", kind: "skill", skillId: "intimidate", cost: 100 },
      {
        id: "navigation-surface",
        kind: "skill",
        skillId: "navigation-surface",
        cost: 100,
      },
      { id: "silent-move", kind: "skill", skillId: "silent-move", cost: 100 },
      {
        id: "survival-10",
        kind: "skill",
        skillId: "survival",
        level: "+10",
        cost: 100,
        prerequisites: "Survival",
      },
      { id: "wrangling", kind: "skill", skillId: "wrangling", cost: 100 },
      {
        id: "crippling-strike",
        kind: "talent",
        talentId: "crippling-strike",
        cost: 100,
        prerequisites: "WS 50",
      },
      {
        id: "resistance-fear",
        kind: "talent",
        talentId: "resistance",
        specialisation: "Fear",
        cost: 100,
      },
      {
        id: "sound-constitution-1",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 100,
      },
      {
        id: "sound-constitution-2",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 100,
      },
      { id: "gamble", kind: "skill", skillId: "gamble", cost: 200 },
      {
        id: "survival-20",
        kind: "skill",
        skillId: "survival",
        level: "+20",
        cost: 200,
        prerequisites: "Survival +10",
      },
      {
        id: "ambidextrous",
        kind: "talent",
        talentId: "ambidextrous",
        cost: 200,
        prerequisites: "Ag 30",
      },
      {
        id: "die-hard",
        kind: "talent",
        talentId: "die-hard",
        cost: 200,
        prerequisites: "WP 40",
      },
      { id: "frenzy", kind: "talent", talentId: "frenzy", cost: 200 },
      {
        id: "melee-chain",
        kind: "talent",
        talentId: "melee-weapon-training",
        specialisation: "Chain",
        cost: 200,
      },
      {
        id: "swift-attack",
        kind: "talent",
        talentId: "swift-attack",
        cost: 200,
        prerequisites: "WS 35",
      },
      {
        id: "beast-hunter",
        kind: "talent",
        talentId: "beast-hunter",
        cost: 200,
        prerequisites: "WS 35, BS 35",
      },
    ],
  },
  {
    id: "legate-investigator",
    name: "Legate Investigator",
    source: SkillSource.IH,
    quote:
      "Did you receive the heretics into your company? Did you swear to them any service? Did you, knowing that they are the foulest of traitors, aid them by deliberate act, by tolerating their presence, or by the sin of silence when knowing of heresy?",
    attribution: "From the Blessed Rituals of Inquiry, Volume IX.",
    description: "",
    requiredCareerIds: ["adept", "arbitrator", "cleric", "guardsman", "imperial-psyker"],
    minimumRank: 4,
    minimumXp: 2_000,
    requirements: {
      requiredSkills: ["literacy"],
      requiresInquisitorOffer: true,
    },
    grantedGear: [
      {
        id: "legature",
        referenceId: "ih-legature",
        name: "Legature",
        description:
          "A formal carta of inquiry stating the locale of investigation and the focus of concern. On presentation and corroboration of a Sigil of Inquiry, it grants the bearer the absolute right to question and examine whoever or whatever they wish.",
      },
      {
        id: "sigil-of-question",
        referenceId: "ih-sigil-of-question",
        name: "Sigil of Question",
        description:
          "A silver icon featuring the sign of a chalice engraved with the symbol of the Inquisition. It demonstrates the Legate Investigator’s remit and authority under the Ordos Calixis. It may be worn as a medallion, carried in a wallet or worn on a finger as a ring, and contains a code-key system for verification and secure data-access if needed.",
      },
    ],
    advances: [
      { id: "command", kind: "skill", skillId: "command", cost: 100 },
      {
        id: "forbidden-cults",
        kind: "skill",
        skillId: "forbidden-cults",
        cost: 100,
      },
      {
        id: "forbidden-heresy",
        kind: "skill",
        skillId: "forbidden-heresy",
        cost: 100,
      },
      {
        id: "forbidden-mutants",
        kind: "skill",
        skillId: "forbidden-mutants",
        cost: 100,
      },
      {
        id: "forbidden-psyker",
        kind: "skill",
        skillId: "forbidden-psyker",
        cost: 100,
      },
      { id: "inquiry", kind: "skill", skillId: "inquiry", cost: 100 },
      {
        id: "inquiry-10",
        kind: "skill",
        skillId: "inquiry",
        level: "+10",
        cost: 100,
        prerequisites: "Inquiry",
      },
      {
        id: "interrogation",
        kind: "skill",
        skillId: "interrogation",
        cost: 100,
      },
      {
        id: "interrogation-10",
        kind: "skill",
        skillId: "interrogation",
        level: "+10",
        cost: 100,
        prerequisites: "Interrogate",
      },
      { id: "scrutiny", kind: "skill", skillId: "scrutiny", cost: 100 },
      {
        id: "scrutiny-10",
        kind: "skill",
        skillId: "scrutiny",
        level: "+10",
        cost: 100,
        prerequisites: "Scrutiny",
      },
      {
        id: "ciphers-inquisition",
        kind: "skill",
        skillId: "ciphers-inquisition",
        cost: 200,
      },
      {
        id: "forbidden-cults-10",
        kind: "skill",
        skillId: "forbidden-cults",
        level: "+10",
        cost: 200,
        prerequisites: "Forbidden Lore (Cults)",
      },
      {
        id: "forbidden-heresy-10",
        kind: "skill",
        skillId: "forbidden-heresy",
        level: "+10",
        cost: 200,
        prerequisites: "Forbidden Lore (Heresy)",
      },
      {
        id: "forbidden-mutants-10",
        kind: "skill",
        skillId: "forbidden-mutants",
        level: "+10",
        cost: 200,
        prerequisites: "Forbidden Lore (Mutants)",
      },
      {
        id: "forbidden-psyker-10",
        kind: "skill",
        skillId: "forbidden-psyker",
        level: "+10",
        cost: 200,
        prerequisites: "Forbidden Lore (Psykers)",
      },
      {
        id: "inquiry-20",
        kind: "skill",
        skillId: "inquiry",
        level: "+20",
        cost: 200,
        prerequisites: "Inquiry +10",
      },
      {
        id: "interrogation-20",
        kind: "skill",
        skillId: "interrogation",
        level: "+20",
        cost: 200,
        prerequisites: "Interrogate +10",
      },
      {
        id: "scholastic-judgement",
        kind: "skill",
        skillId: "scholastic-judgement",
        cost: 200,
      },
      {
        id: "scrutiny-20",
        kind: "skill",
        skillId: "scrutiny",
        level: "+20",
        cost: 200,
        prerequisites: "Scrutiny +10",
      },
      {
        id: "air-of-authority",
        kind: "talent",
        talentId: "air-of-authority",
        cost: 200,
        prerequisites: "Fel 30",
      },
      {
        id: "talented-inquiry",
        kind: "talent",
        talentId: "talented",
        specialisation: "Inquiry",
        cost: 200,
        prerequisites: "Inquiry",
      },
      {
        id: "talented-interrogation",
        kind: "talent",
        talentId: "talented",
        specialisation: "Interrogation",
        cost: 200,
        prerequisites: "Interrogation",
      },
    ],
  },
  {
    id: "malfian-bloodsworn",
    name: "Malfian Bloodsworn",
    source: SkillSource.IH,
    quote:
      "Now be a nice gent and come here and bleed on this warrant for me, eh? Then I’ll make it quick for ye, otherwise I’ll get a bit put out, and well… I hate swabbing the floor and getting nice parchment dirty. Seems so… undignified like.",
    attribution: "Auric Kenge, Chartered Bloodsworn.",
    description:
      "A holder of a Bloodsworn Charter has certain rights above those of a common hired gun. The warrant enables them to bear arms in the hive where others would not, access legal record, enter private dwellings, and even avoid interference from local enforcers and armsmen in pursuit of their warrants. These powers have limits and do not extend to the holdings or persons of the Adepta or Malfi’s rulers.",
    requiredCareerIds: ["assassin", "scum", "guardsman", "arbitrator"],
    minimumRank: 5,
    minimumXp: 3_000,
    requirements: {
      otherRequirements: [
        "Guardsmen or Arbitrators must no longer be in overt Imperial service.",
        "Must gain a charter from the Blood Guild of Malfi.",
      ],
    },
    grantedEliteAdvances: ["bloodsworn-charter"],
    advances: [
      { id: "charm", kind: "skill", skillId: "charm", cost: 100 },
      {
        id: "common-administratum",
        kind: "skill",
        skillId: "common-administratum",
        cost: 100,
      },
      { id: "deceive", kind: "skill", skillId: "deceive", cost: 100 },
      { id: "inquiry", kind: "skill", skillId: "inquiry", cost: 100 },
      {
        id: "inquiry-10",
        kind: "skill",
        skillId: "inquiry",
        level: "+10",
        cost: 100,
        prerequisites: "Inquiry",
      },
      {
        id: "inquiry-20",
        kind: "skill",
        skillId: "inquiry",
        level: "+20",
        cost: 100,
        prerequisites: "Inquiry +10",
      },
      { id: "interrogation", kind: "skill", skillId: "interrogation", cost: 100 },
      {
        id: "interrogation-10",
        kind: "skill",
        skillId: "interrogation",
        level: "+10",
        cost: 100,
        prerequisites: "Interrogation",
      },
      { id: "search", kind: "skill", skillId: "search", cost: 100 },
      {
        id: "search-10",
        kind: "skill",
        skillId: "search",
        level: "+10",
        cost: 100,
        prerequisites: "Search",
      },
      { id: "security", kind: "skill", skillId: "security", cost: 100 },
      {
        id: "security-10",
        kind: "skill",
        skillId: "security",
        level: "+10",
        cost: 100,
        prerequisites: "Security",
      },
      { id: "shadowing", kind: "skill", skillId: "shadowing", cost: 100 },
      {
        id: "shadowing-10",
        kind: "skill",
        skillId: "shadowing",
        level: "+10",
        cost: 100,
        prerequisites: "Shadowing",
      },
      { id: "survival", kind: "skill", skillId: "survival", cost: 100 },
      { id: "tracking", kind: "skill", skillId: "tracking", cost: 100 },
      {
        id: "tracking-10",
        kind: "skill",
        skillId: "tracking",
        level: "+10",
        cost: 100,
        prerequisites: "Tracking",
      },
      {
        id: "basic-bolt",
        kind: "talent",
        talentId: "basic-weapon-training",
        specialisation: "Bolt",
        cost: 100,
      },
      {
        id: "decadence",
        kind: "talent",
        talentId: "decadence",
        cost: 100,
        prerequisites: "T 30",
      },
      {
        id: "hard-target",
        kind: "talent",
        talentId: "hard-target",
        cost: 100,
        prerequisites: "Ag 40",
      },
      {
        id: "heightened-senses-hearing",
        kind: "talent",
        talentId: "heightened-senses",
        specialisation: "Hearing",
        cost: 100,
      },
      {
        id: "heightened-senses-sight",
        kind: "talent",
        talentId: "heightened-senses",
        specialisation: "Sight",
        cost: 100,
      },
      {
        id: "iron-jaw",
        kind: "talent",
        talentId: "iron-jaw",
        cost: 100,
        prerequisites: "T 40",
      },
      {
        id: "jaded",
        kind: "talent",
        talentId: "jaded",
        cost: 100,
        prerequisites: "WP 30",
      },
      {
        id: "peer-underworld",
        kind: "talent",
        talentId: "peer",
        specialisation: "Underworld",
        cost: 100,
        prerequisites: "Fel 30",
      },
      {
        id: "pistol-bolt",
        kind: "talent",
        talentId: "pistol-training",
        specialisation: "Bolt",
        cost: 100,
      },
      {
        id: "rapid-reaction",
        kind: "talent",
        talentId: "rapid-reaction",
        cost: 100,
        prerequisites: "Ag 40",
      },
      {
        id: "street-fighting",
        kind: "talent",
        talentId: "street-fighting",
        cost: 100,
      },
      { id: "barter", kind: "skill", skillId: "barter", cost: 200 },
      { id: "carouse", kind: "skill", skillId: "carouse", cost: 200 },
      { id: "evaluate", kind: "skill", skillId: "evaluate", cost: 200 },
      {
        id: "forbidden-mutants",
        kind: "skill",
        skillId: "forbidden-mutants",
        cost: 200,
      },
      {
        id: "nerves-of-steel",
        kind: "talent",
        talentId: "nerves-of-steel",
        cost: 200,
      },
      { id: "paranoia", kind: "talent", talentId: "paranoia", cost: 200 },
      {
        id: "sound-constitution-1",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 200,
      },
      {
        id: "sound-constitution-2",
        kind: "talent",
        talentId: "sound-constitution",
        cost: 200,
      },
      {
        id: "talented-inquiry",
        kind: "talent",
        talentId: "talented",
        specialisation: "Inquiry",
        cost: 200,
        prerequisites: "Inquiry",
      },
      {
        id: "two-weapon-wielder-ballistic",
        kind: "talent",
        talentId: "two-weapon-wielder",
        specialisation: "Ballistic",
        cost: 300,
        prerequisites: "BS 35, Ag 35",
      },
      {
        id: "two-weapon-wielder-melee",
        kind: "talent",
        talentId: "two-weapon-wielder",
        specialisation: "Melee",
        cost: 300,
        prerequisites: "WS 35, Ag 35",
      },
    ],
  },
];
